### ISSUE TITLE
Parsed response is displaying the raw response doubled

### ISSUE THREAD

**Issue by RanGold** [jarrodek/ChromeRestClient#800] opened 2016-09-13 11:18 UTC
For example, the following raw response:
+------------------------------------------------------------------------------------------------------------------------------+
| name                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------+
| "×××× 120x180 ×¡"×, 4A4"                                                                                                      |
+------------------------------------------------------------------------------------------------------------------------------+
1 rows

**Comment by jarrodek** [comment] 2016-09-13 14:06
Hi,

Which version of the app are you using right now? It was fixed and released yesterday.

**Comment by jarrodek** [comment] 2016-09-13 14:07
Duplicate of the #778

**Closed** 2016-10-25 12:50 UTC
Labels: awaiting-response
