### ISSUE TITLE
Not able to test my api on Rest Client

### ISSUE THREAD

**Issue by kachhawayamehulgmailcom** [jarrodek/ChromeRestClient#960] opened 2017-02-20 12:53 UTC
Your description here
I want to test api some parameters are there like id,name,businessid,messages...etc.. and i use one file upload.

## Expected outcome
All data successfully updated at database.

## Actual outcome
While upload a file and test it will not carry data, and without uploading file it working fine,all data saved in database , but imageurl column in database is null.
same scenario working fine few days ago.

## Versions
App: 8.19.60.296-stable
Chrome: 56.0.2924.87
Platform: Windows (8.1)

## Steps to reproduce
1. How to test it.
2. How can i get running back scenario like few days ago i am able to do it.
3. What changes do i need to make in rest client.

**Comment by jarrodek** [comment] 2017-02-20 20:22
Hi,

This is confirmed bug in Chrome. And this is duplicate of #945. I'm currently working on a solution. 

I'm closing it as a duplicate.

**Closed by jarrodek** 2017-02-20 20:22 UTC
