### ISSUE TITLE
Incorrect port number received in response, after upgrade.

### ISSUE THREAD

**Issue by subhban01** [jarrodek/ChromeRestClient#565] opened 2016-04-20 14:34 UTC
Your description here
I'm hitting an URL's resourceIndex at port 8888. (GET)

## Expected outcome
What should happen?
Should receive all resources with the base URI remaining the same.

## Actual outcome
What happened?
Base URI port number changes to 80

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. Enter URL's resourceIndex (port 8888)
2. Incorrect port number received in response
3.

**Comment by jarrodek** [comment] 2016-04-20 14:57
Hi thank you for an issue report.

I can't reproduce the error though. Can you paste here logs from the request? Logs are in the left nav panel at the bottom.

**Comment by tomviner** [comment] 2016-04-21 11:03
You're not adding non-default ports to the HOST header:
![image](https://cloud.githubusercontent.com/assets/167319/14706752/6f549ef0-07b8-11e6-91c2-69e21448eeb6.png)

Log snippet:
```json
    {
        "logs": "[\"Generated message to send\\n\",\"GET / HTTP/1.1\\r\\nHOST: portquiz.net\\r\\n\\r\\n\"]",
        "stack": [
            "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
            "    at generateMessage.then (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24581:14)"
        ],
        "time": 1461236292445,
        "type": "log"
    },
    {
        "logs": "[\"Connected to socked for host: \",\"portquiz.net\",\" and port \",8080]",
        "stack": [
            "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
            "    at promise.then (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24331:14)"
        ],
        "time": 1461236292442,
        "type": "log"
    },
    {
        "logs": "[\"Connecting to %s:%d\",\"portquiz.net\",8080]",
        "stack": [
            "    at SocketFetch.log (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24463:19)",
            "    at Object.chrome.sockets.tcp.create [as callback] (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:24320:12)",
            "    at safeCallbackApply (extensions::sendRequest:21:15)",
            "    at handleResponse (extensions::sendRequest:72:7)"
        ],
        "time": 1461236292429,
        "type": "log"
    },
```

Full log: https://gist.github.com/tomviner/6a3ad0ac8e9429eb66ec64c3bebffce8

Note Chrome browser, does the right thing:

![image](https://cloud.githubusercontent.com/assets/167319/14706787/a28f9612-07b8-11e6-9ee6-a696b2d2cf4e.png)

**Comment by jarrodek** [comment] 2016-04-21 11:11
Hi, Thanks for the reports.
As you can see in the log the connection is made on port 8080 - not 80 - as you intended. Therefore the app is doing good.
See the log: 

> Connected to socked for host: portquiz.net and port 8080

Then the app taking a response and displays it. Not sure if I understand issue correctly. What do you mean by "Should receive all resources with the base URI remaining the same."? There is only one resource to be fetched - the one in the URL field. The app doesn't care for any other resources embedded in the response since it's not a purpose of the app.

Please clarify a bit.

**Comment by tomviner** [comment] 2016-04-21 13:01
The underlying connection is made to the correct port, but the value of the host header is incorrect. So server code that relies on reading the host header to do things like give the user an absolute url, will be incorrect. This applies to my own code: the url I form comes back missing the port.

This RFC confirms the port should be included in the host header (unless it's the default http on 80 / https on 443): https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

And this was the behaviour of the previous version of ARC. And of Chrome browser itself, as confirmed in my screenshot above.

Does that help clarify?

**Comment by tomviner** [comment] 2016-04-21 20:49
I didn't really highlight this before, the actual content of http://portquiz.net:8088/ that's returned in ARC, confirms it thinks I connected on port 80, because it reads the host header (and no port means 80):

![image](https://cloud.githubusercontent.com/assets/167319/14723791/b64edbac-080a-11e6-88e6-4485d22b5f55.png)

**Comment by jarrodek** [comment] 2016-04-23 22:10
Thanks for pointing this out. It is actually a bug and the transport library is not consistent with the spec.
I'll fix it with high priority.

**Comment by jarrodek** [comment] 2016-04-23 22:12
There is a related issue in the transport library that you can follow to be notified when the bug is fixed. https://github.com/jarrodek/socket-fetch/issues/8

**Comment by tomviner** [comment] 2016-04-23 22:31
Thanks for recognising this, and taking swift action.

**Closed** 2016-04-23 22:54 UTC
Labels: bug

**Comment by subhban01** [comment] 2016-04-27 05:20
Thanks for fixing this!
