### ISSUE TITLE
Doesn't maintain session in between requests

### ISSUE THREAD

**Issue by erickoon** [jarrodek/ChromeRestClient#504] opened 2016-04-18 21:35 UTC
Doesn't remember to use the same session cookies for multiple requests

## Expected outcome
What should happen?
Like before ... if its the same domain ... use the same cookies.

## Actual outcome
What happened?
Subsequence requests doesn't use the same session.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. Hit an API that generates session id cookies
2. Hit a different API but same domain
3.

**Comment by jarrodek** [comment] 2016-04-18 21:49
Duplicate of #487

**Closed by jarrodek** 2016-04-18 21:49 UTC
