### ISSUE TITLE
Does not appear in browser window

### ISSUE THREAD

**Issue by davideakes** [jarrodek/ChromeRestClient#567] opened 2016-04-20 15:02 UTC
Your description here

## Expected outcome
What should happen?
I should be able to tab browse.

## Actual outcome
What happened?
I cannot tab browse.

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)

## Steps to reproduce
1. Open it.
2. See that there are no tabs
3. Wish to roll back to previous version where I could have tabs.

**Comment by jarrodek** [comment] 2016-04-20 15:05
Hi,

Thanks for issue report.

I wrote an article about that: http://restforchrome.blogspot.co.uk/2016/04/advanced-rest-client-is-not-in-tab.html

It is a duplicate of #510

**Closed by jarrodek** 2016-04-20 15:05 UTC
