### ISSUE TITLE
Not able to make mutual auth REST calls

### ISSUE THREAD

**Issue by cmouli84** [jarrodek/ChromeRestClient#465] opened 2016-04-11 17:26 UTC
When trying to make mutual auth REST calls (requires client cert), the call is failing with error "There was an error during the request. An SSL protocol error occurred". In the earlier version, it was using the certification I had in Personal store via chrome. That does not work anymore.

## Expected outcome
Mutual auth REST call should use certificate from Personal store

## Actual outcome
Displays error "There was an error during the request. An SSL protocol error occurred"

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. Make mutual auth REST call which requires client cert

**Comment by jarrodek** [comment] 2016-04-11 17:33
Duplicate of #432

**Closed by jarrodek** 2016-04-11 17:33 UTC
