### ISSUE TITLE
History Tab

### ISSUE THREAD

**Issue by jasnajayaraj** [jarrodek/ChromeRestClient#377] opened 2016-02-08 10:57 UTC
We are not able to search for a particular rest call by providing a stringIT seems to have changed to 
Exact match of the endpoint string rather than using contains.This is in version 4.11

In 4.10 we are not able to enter any data in the Request textbox.

**Comment by jarrodek** [comment] 2016-02-08 18:38
Textbox issue is a duplicate of #376 
In 4.11 I switched database engine to IndexedDB. It's not so convenient as WebSQL but it is required for apps to migrate to indexDB. History and saved tabs now searching for using "startsWith" algorithm. I'll try figure it out how to perform full search query in indexeddb later this month.

**Closed** 2016-02-08 21:38 UTC

**Comment by jasnajayaraj** [comment] 2016-02-09 04:30
Thanks a ton :)
