### ISSUE TITLE
Trying to send request via XML Gate Way doesn't ask us of choosing existing secure certificates 

### ISSUE THREAD

**Issue by ArtemBober** [jarrodek/ChromeRestClient#584] opened 2016-04-21 08:19 UTC
App doesn't propose the variants of choosing existing secure certificates 

## Expected outcome
App should propose the variants of choosing existing secure certificates 

## Actual outcome
There was an error during the request
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. Insert some secured Link (you already have installed secure certificate for it)
2. put correct request 
3. click "Send" button

**Comment by Kathleensebree** [comment] 2016-04-21 15:37
I'm also receiving this error.

**VERSIONS**
app: 7.7.26.168
Chrome: 50.0.2661.75 m
Platform: Windows (10)

Steps to reproduce are the same as original post.

**Comment by jarrodek** [comment] 2016-04-23 22:06
Hi,
Thank you for issue report. This is duplicate of #432.

Please refer to the cr-bug (https://bugs.chromium.org/p/chromium/issues/detail?id=603104) for reasons why it is not going to be fixed in the app.

I'm closing it as wont fix.

**Closed by jarrodek** 2016-04-23 22:06 UTC
