### ISSUE TITLE
Can't save to existing project

### ISSUE THREAD

**Issue by IANicole** [jarrodek/ChromeRestClient#385] opened 2016-02-11 01:18 UTC
I keep trying to save an endpoint to an existing project, but for some reason it just stays in my "saved" list instead. 

I've made sure I select the project and I've tried by doing both "overwrite" and "save as new".

**Comment by jarrodek** [comment] 2016-02-11 12:05
Duplicate of #382

**Closed by jarrodek** 2016-02-11 12:05 UTC
