### ISSUE TITLE
HTTP Response is 200 or 500

### ISSUE THREAD

**Issue by twallace-apptium** [jarrodek/ChromeRestClient#989] opened 2017-03-29 19:10 UTC
The Service I'm testing response with 201 with an location URI, either show because it only show HTTP 200 with response data

## Expected outcome
HTTP 201 with location URI and additional response data

## Actual outcome
HTTP 200

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Mac OS X (10_12_3)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2017-04-07 12:07
Hi,

Thank you for issue report.
I can't reproduce the problem. The app is reporting `201` when server sends `201` and `200` when it sends `200`.
Your server must have sent the `200` instead of `201` status code. Application just passing the response data from the transport to the view so it can't be an issue with the app.

You can also try running the https://httpbin.org/status/201 to see that it works as expected.

I'm closing it but feel free to comment.

**Closed by jarrodek** 2017-04-07 12:07 UTC
