### ISSUE TITLE
input select project dont appears

### ISSUE THREAD

**Issue by brunocasado** [jarrodek/ChromeRestClient#479] opened 2016-04-13 17:38 UTC
When we need save the request in a project, the project input dont appear.
OBS: After write some text in new project input and clean it, the input appears. After this i think that the problem solved. Maybe the problem happen because the prev structure?

## Expected outcome
have input to select existing project

## Actual outcome
Input dont appear

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.112
Platform: Linux (-)

## Steps to reproduce
1. Create a new request
2. save
3. look for project input (dont appear)

**Comment by jarrodek** [comment] 2016-04-13 18:52
It looks like it is a duplicate of #478

**Comment by brunocasado** [comment] 2016-04-13 18:56
@jarrodek this two issues are similars. One complements the each other.

**Closed** 2016-04-15 14:03 UTC
Labels: bug
