### ISSUE TITLE
[Minor] Going back from settings pannels in small window glitches the GUI

### ISSUE THREAD

**Issue by danielhickman** [jarrodek/ChromeRestClient#918] opened 2016-12-03 00:17 UTC
https://gfycat.com/FarflungUnlinedBinturong

Resizing or opening another panel fixes it.

## Versions
App: 8.19.60.296-stable
Chrome: 56.0.2924.10
Platform: Windows (10)
Display: 2160p scaled 1.5x

## Steps to reproduce
1. Resize the window
2. Open magic variables
3. Hit the back arrow

**Comment by jarrodek** [comment] 2016-12-04 14:54
Hi,

Thank you for issue report.
I can't reproduce this problem. However, I know there may be an issues with animated panels I'm using. I already removed animation from main screens and I will remove it from the settings screen as well. I just forgotten to do this earlier.

**Comment by jarrodek** [comment] 2017-01-16 15:07
This is resolved in the develop branch. All animation has been removed from the settings panel.
The update to the store should be very soon.

**Closed by jarrodek** 2017-01-16 15:07 UTC
Labels: bug
