### ISSUE TITLE
Property value changes in JSON Tab view

### ISSUE THREAD

**Issue by dionedomingo** [jarrodek/ChromeRestClient#734] opened 2016-07-29 00:10 UTC
Your description here

I noticed property values are not showing the correct property value in JSON Tab. 

Take this JSON as an example. 
https://dl.dropboxusercontent.com/u/413954120/test.json

This is what i see when i'am switching between **Parsed** and **JSON** tabs

**Parsed TAB**
... "order_number": 146312323488002033 ...
<img width="1207" alt="screenshot 2016-07-29 01 47 55" src="https://cloud.githubusercontent.com/assets/99091/17233458/4bf930ae-5530-11e6-8e6d-9c1cf4845b4f.png">

**JSON TAB**
When switching to JSON view the last two digit changes from 33 to 50
... "order_number": 146312323488002050 ...

<img width="1189" alt="screenshot 2016-07-29 01 48 13" src="https://cloud.githubusercontent.com/assets/99091/17233459/4c00c666-5530-11e6-9ac2-8cb31e17389e.png">

## Expected outcome
What should happen?

Those last two numbers in order_number shouldn't change.

## Actual outcome
What happened?

order_number are changed from 33 to 50 in JSON tab

## Versions
App: 7.26.44.220-stable
Chrome: 51.0.2704.103
Platform: Mac OS X (10_11_0)

## Steps to reproduce
1. Use the json url and Click Send
2. Try switching between Parsed Tab and JSON Tab
3.

**Comment by jarrodek** [comment] 2016-08-08 16:35
Hi,

Thank you for issue report. It is a duplicate of issue #234.  It's not an app error but it's about how JavaScript handles big numbers. It basically looses a precision and final information can be different. Probably that's why many APIs uses numeric IDs as string (Facebook, Twitter...).

It's very hard to fix it because it would require to use a custom JSON parser and that would kill the performance. I'm keeping this issues and it should be fixed somehow but it may not be very fast fix.

**Closed** 2016-08-08 16:35 UTC
Labels: Duplicate
