### ISSUE TITLE
Encode and Decode URL mistreat '+' sign

### ISSUE THREAD

**Issue by Pearseak** [jarrodek/ChromeRestClient#1044] opened 2017-09-07 08:02 UTC
If we decode an url with + it'll become space and if we encode it again it'll become %20 which has nothing to do with '+' in the first place

It doesn't convert + to %2B in query parameters,not sure if we need literal string option

**Comment by jarrodek** [comment] 2017-09-07 18:44
Hi,
Thank you for the issue report.
The issue is with current version. New version (still in development) has this issue resolved.
The update will be released very soon.

I'm closing it as fixed.

**Closed by jarrodek** 2017-09-07 18:44 UTC
