### ISSUE TITLE
Basic Authentication of a URL get mode

### ISSUE THREAD

**Issue by enarendar9** [jarrodek/ChromeRestClient#827] opened 2016-10-27 19:35 UTC
I am accessing a URL in basic authentication mode (i am intercepting with burp suite) I am providing the correct user ID and password. The error is 403, does it mean that there is no access to the URL from outside network. Any inputs are appreciated

**Comment by enarendar9** [comment] 2016-10-27 19:38
403, Forbidden
Date: Thu, 27 Oct 2016 19:37:23 GMT
Content-Encoding: gzip
Server: nginx/1.4.6 (Ubuntu)
Connection: keep-alive
Transfer-Encoding: chunked
Content-Type: text/html

**Comment by jarrodek** [comment] 2016-10-28 12:15
Hi,

Thank you for issue report.
I'm not sure how to reproduce this. Are you passing user id and password in the URL of in the authorization header? 403 means that you are not authorised to see the resource and you must authorise yourself first. If that is a basic authorization you have to pass proper header to the request.
Please, give me more details.

**Comment by enarendar9** [comment] 2016-10-30 15:04
I had faced the issue of 403 because of restricted access to the resource.
I believe now i have the access, but now the issue is 401 ... Is there a way i can bypass authentication even if i have the correct credentials.?

**Comment by jarrodek** [comment] 2016-11-07 12:45
If you have correct credentials you should be able to get the resource. Just pass proper autorization header depending on a authentication system. For example for basic authentication where you have just a username and a password you should set the authorization header like this:
```
authorization: Basic dGVzdDp0ZXN0
```
Where `dGVzdDp0ZXN0` is a base64 encoded username : password. Other authentication methods require different approach and different header setup. If you tell me what's an authentication system on your application then I can suggest you appropriate approach.

Anyway I doesn't looks like the issue with the app so eventually I'll close it as WAI.

**Comment by jarrodek** [comment] 2016-11-30 01:14
I'm closing this per giving a response and lack of evidence of issue with the app.

**Closed by jarrodek** 2016-11-30 01:14 UTC
Labels: awaiting-response, WAI
