### ISSUE TITLE
New window doesn't share session. 

### ISSUE THREAD

**Issue by rtugeek** [jarrodek/ChromeRestClient#473] opened 2016-04-13 08:17 UTC
Seems the new window doesn't share session with chrome tabs. Is there any way to solve this issue?

**Comment by jarrodek** [comment] 2016-04-13 18:50
Chrome apps do not share the same session with Chrome. However I may be able to create an extension to share cookie data between the app and chrome. Unfortunately it will require to install additional extension. I'll explore this topic.

**Comment by velo** [comment] 2016-04-13 22:53
This is a major problem for me as well

Is there a way to get it as tab again?

**Comment by jarrodek** [comment] 2016-04-14 08:37
There's no point of doing it since the chrome legacy apps (previous version) are deprecated in chrome and already blocked in Chrome Web Store.

**Comment by velo** [comment] 2016-04-14 21:38
If i knew I wouldn't have upgrade it... =(

**Comment by jarrodek** [comment] 2016-04-18 21:45
Duplicate of #472

**Closed by jarrodek** 2016-04-18 21:45 UTC
Labels: enhancement
