### ISSUE TITLE
Response not parsed and displayed

### ISSUE THREAD

**Issue by swarajpanicker** [jarrodek/ChromeRestClient#507] opened 2016-04-18 23:50 UTC
I sent a JSON put request to my application REST web service and the application logs show that the request was received and response was sent but the new version of ARC is still waiting for the response. This used to work perfectly in the old version, but something has gone wrong with this new version. Tried the same web service on some other REST client in Firefox and the same are working fine and showing response properly.

**Comment by swarajpanicker** [comment] 2016-04-18 23:55
![arc_response_issue](https://cloud.githubusercontent.com/assets/12135435/14623357/891a4702-0625-11e6-9a5c-882fd197afe5.jpg)

**Comment by swarajpanicker** [comment] 2016-04-18 23:56
Have masked the url and response contents for security reasons. The request is fired and server has responded but the ARC is still waiting for it. Other clients don't have issue with same web service.

**Comment by jarrodek** [comment] 2016-04-19 00:40
In the nav (on left) panel there is an log viewer (in dropdown menu in the bottom). Do you see any error log in it? Alternatively if there are any error log in the console if you [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) the app?

**Comment by swarajpanicker** [comment] 2016-04-19 22:04
PFB the logs. It seems to fail at respones due to parsing error i believe:

Created socket 18
app.logger.js:59 Connecting to ****
app.logger.js:59 Connected to socked for host:  ****  and port  ****
app.logger.js:59 Generated message to send
 PUT <****URL****> HTTP/1.1
HOST: ****
content-type: application/json
content-length: 933

***********WS REQUEST REMOVED****************

app.logger.js:59 Sending message.
app.logger.js:59 Written message. Bytes sent: 1051
app.logger.js:59 Has socket data
app.logger.js:59 Processing status
app.logger.js:59 Processing headers
app.logger.js:59 Received headers list Date: Tue, 19 Apr 2016 22:00:26 GMT
Server: Apache/2.2.3 (Red Hat)
Content-Length: 180
Connection: close
Content-Type: application/json Object {Date: "Tue, 19 Apr 2016 22:00:26 GMT", Server: "Apache/2.2.3 (Red Hat)", Content-Length: "180", Connection: "close", Content-Type: "application/json"}
app.logger.js:59 Processing body
app.logger.js:59 Creating new body
app.logger.js:59 Response ready. Calling it.
app.logger.js:59 Disconnect
**undefined:1 Uncaught (in promise) SyntaxError: Unexpected token <**

**Comment by jarrodek** [comment] 2016-04-20 11:11
Oh, In this case it is duplicate of #426.
Empty responses where the content-type is json were caused an error in the Response object and this error wasn't catched. 
It is fixed in a feature branch and soon will be merged and released.

So now I'll close this issue.

**Closed by jarrodek** 2016-04-20 11:11 UTC
