### ISSUE TITLE
JSON Payload Not sent to API endpoint

### ISSUE THREAD

**Issue by cnadig-cc** [jarrodek/ChromeRestClient#503] opened 2016-04-18 21:27 UTC
Your description here
APIs not receiving the payload.

## Expected outcome
What should happen?
The JSON Payload should be received in the API. 

## Actual outcome
What happened?
But despite setting content-type header, nothing is received.

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Mac OS X (10_11_4)

**Comment by jarrodek** [comment] 2016-04-18 21:43
Can you open response's **Request headers** tab and paste "Source message" content?
![image](https://cloud.githubusercontent.com/assets/3320020/14620798/c1662370-05b6-11e6-95a5-d147bc29a458.png)
It is a message directly sent to server via the socket. It will help debug the issue.

**Comment by cnadig-cc** [comment] 2016-04-18 23:09
![screen shot 2016-04-18 at 4 08 20 pm](https://cloud.githubusercontent.com/assets/13526317/14622594/ddaffcd6-057f-11e6-9f3b-332521b3db9d.png)

**Comment by jarrodek** [comment] 2016-04-19 00:37
What I see here is that the message is send to the server correctly. This is the proper HTTP message that should be send to server. You should check if the server code recognize input correctly. Maybe your server recognize different content-type than `application-json`. 
I'd be inclined to close this as work as intended.

**Comment by jarrodek** [comment] 2016-05-09 19:00
I'm closing it because of lack of activity.

**Closed by jarrodek** 2016-05-09 19:00 UTC
Labels: WAI
