### ISSUE TITLE
Missing Timeout settings

### ISSUE THREAD

**Issue by marcocast** [jarrodek/ChromeRestClient#553] opened 2016-04-20 08:01 UTC
When I run long REST requests (more than 40-ish seconds) the client fails with a timeout exception.
This was not happening in the previous version.

## Expected outcome
I should be able to increase the timeout in the settings.

## Actual outcome
the client fails with a timeout exception.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Mac OS X (10_11_3)

## Steps to reproduce
1.  Send a REST GET or POST or DELETE request that takes 1 minute.

**Comment by jarrodek** [comment] 2016-04-20 12:03
Duplicate of #502

**Closed by jarrodek** 2016-04-20 12:03 UTC
