### ISSUE TITLE
ARC Request Body no longer allows user to paste in data

### ISSUE THREAD

**Issue by mehrenberger** [jarrodek/ChromeRestClient#1105] opened 2017-11-13 12:44 UTC
Your description here: The ARC Request Body no longer allows the user to paste data into their existing query.  Even when the data to be replaced specifically selected, on the paste the entire query gets replaced with the data, not just the intended/selected field.

## Expected outcome
User should be allowed to paste data into their query at the point where their cursor is sitting when they perform the action.

## Actual outcome
Entire query gets replaced with the data intended to be put into a specific field.

## Versions
App: 10.0.10
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

## Steps to reproduce
1.  Have any existing query
2.  Copy data from somewhere else
3.  Attempt to paste the data into the query
a. First attempt is just selecting the piece of data to be replaced and pasting over it
b. Second attempt is selecting and deleting the existing data, then attempting to paste new data into the field
![arcrequestcopypaste](https://user-images.githubusercontent.com/9273088/32726249-e9dd7114-c83d-11e7-85ad-7984710dc2dc.gif)

**Comment by jarrodek** [comment] 2017-11-18 06:46
Hi,
Thank you for the issue report. It is a duplicate of #1103

**Closed by jarrodek** 2017-11-18 06:46 UTC

**Comment by mehrenberger** [comment] 2017-11-18 13:45
Thank you for the followup!

Mary
