### ISSUE TITLE
Unable to import the exported file of Advanced REST client 

### ISSUE THREAD

**Issue by Vemula-Vivek** [jarrodek/ChromeRestClient#927] opened 2016-12-14 06:20 UTC
Your description here
I am changing to new laptop. So, I have exported the data from "Advanced REST Client" tool of old laptop which was exported to a .json file format. Now am trying to import this data into my new laptop where it is failing with "Unable to parse the file" exception.
## Expected outcome
The import operation should be succeeded without any errors.

## Actual outcome
An exception "Unable to parse the file" is displayed.

## Versions
App: 8.19.60.296-stable
Chrome: 55.0.2883.87
Platform: Windows (7)

## Steps to reproduce
1. Export the data from Advanced REST client tool of old laptop.
2. Copy the exported file to new laptop.
3. Import the exported file to Advanced REST client tool in new laptop.
![image](https://cloud.githubusercontent.com/assets/24560967/21171632/4fd5ba6e-c1f3-11e6-9ddc-784a33218f08.png)
![image](https://cloud.githubusercontent.com/assets/24560967/21171626/4986342c-c1f3-11e6-82ab-5865006f32fd.png)

**Comment by jarrodek** [comment] 2017-01-06 19:40
Hi,

Thank you for issue report.
I believe it is the same as #919. Can you please also answer the question for my first comment in this issue? It will help me debug the problem quickly.

**Comment by jarrodek** [comment] 2017-01-15 20:05
It looks like a duplicate of #911 I'll close it as a duplicate but be free to reopen if needed.

**Closed by jarrodek** 2017-01-15 20:05 UTC
Labels: awaiting-response
