### ISSUE TITLE
An SSL protocol error ocurred

### ISSUE THREAD

**Issue by sawilde** [jarrodek/ChromeRestClient#466] opened 2016-04-12 05:36 UTC
Your description here
When I try to talk to my API using ARC it returns "An SSL protocol error ocurred". This only happens with the new latest ARC.

## Expected outcome
It should work

## Actual outcome
Error

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
Hard to describe as it is a private API but I suspect it is because the API is asking for a certificate; optional as we also support OAuth if supplied.

**Comment by jarrodek** [comment] 2016-04-12 11:05
OAuth support is planned. 

Is this a self-signed certificate? If yes it should be installed in Chrome. 
Will this information helps: http://restforchrome.blogspot.co.uk/2016/04/advanced-rest-client.html?

**Comment by sawilde** [comment] 2016-04-12 11:21
I'll give it a try - the certificate does work normally but not when I am using ARC. If I use postman then I get the certificate challenge which I can ignore (and use OAuth) or accept and use the certificate for authorisation purposes.

**Comment by sawilde** [comment] 2016-04-13 03:36
I get this error

![image](https://cloud.githubusercontent.com/assets/297165/14482129/9c509806-017c-11e6-9c79-2ad9d56630b3.png)

I suspect it is related to the client cert but can't work out how to work around it

**Comment by jarrodek** [comment] 2016-04-13 13:04
This kind of error comes from Chrome's socket implementation. It's code is: `SSL_PROTOCOL_ERROR, 107`. I read some about it and it doesn't look like an app's error. I hound an issue on [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=41591) that reletes to it but it was closed unresolved. Is it possible that the server configuration is invalid, you're behind a proxy or do not have SSL 2/3 support enabled in your system? Not sure how to approach this.

**Comment by sawilde** [comment] 2016-04-13 23:07
It doesn't seem to affect chrome itself (I get a challenge) not postman another tool I can use to do the same type of requests.

**Comment by jarrodek** [comment] 2016-04-14 14:59
Postman have different approach for making a request. It's less elastic and do not gives you full control  over request and response headers but it accept certificates errors when challenged.

**Comment by sawilde** [comment] 2016-04-14 21:51
Perhaps but I never had this issue before with ARC until the recent one (that runs in it's own process perhaps?)

**Comment by jarrodek** [comment] 2016-04-15 09:19
It definitely is. Moreover Chrome team is against relaxing security policy for apps - even if Chrome itself allowing to do this.
I will try to fix this but since I don't know what really happened it may be difficult. You can try [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) the app to check for any errors and pass it to me but because of the error code I'm not sure if there will be any.

**Comment by enoex** [comment] 2016-04-16 17:54
I also am having this problem, which makes ARC unusable. The previous version worked fine. (I require https requests and for localhost use self signed certs).

You can reproduce this by creating a self signed certificate (http://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl). Perhaps, like how browsers prompt to accept self signed certs, there needs to be an option to accept self signed certificates.

**Comment by sawilde** [comment] 2016-04-16 21:33
FYI: My certs are not self-signed and I have the full cert chain installed locally

**Comment by jarrodek** [comment] 2016-04-17 10:51
@enoex Self-signed certificates works when you install the certificate in Chrome. Otherway the app do not have access to it.

**Comment by jarrodek** [comment] 2016-04-17 10:55
@sawilde It may be Chrome issue with SSL. The app may throw this error when trying to secure the connection. There is very little I can do in the app to fix that.

**Comment by sawilde** [comment] 2016-04-18 02:55
@jarrodek other than prompting me to select a certificate I don't have any other errors in Chrome

**Comment by michol33** [comment] 2016-04-19 11:51
I am also seeing the same issue as @sawilde. It is a private API that requires an SSL certificate(not self signed). Since upgrading, I can no longer use ARC. I can use Postman or Chrome itself with no problems, meaning it correctly prompts for my client certificate.

**Comment by traverjc** [comment] 2016-05-02 14:00
Same thing here...sometimes (first time?) I get the following. Also, like others, I'm not prompted for certificate like I was before upgrading.

![image](https://cloud.githubusercontent.com/assets/19150993/14956234/3c6a1a3a-1044-11e6-95cb-531361c845b6.png)

**Comment by jarrodek** [comment] 2016-05-04 22:46
@traverjc and actually all who are interested in this issue, please check [this issue in cr-bug](https://bugs.chromium.org/p/chromium/issues/detail?id=557087#c6) and [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=563687) and star them so maybe Chromium team will implement cert prompting when making a connection.

**Comment by glfp** [comment] 2016-05-13 06:11
Same bug for me. All work with previous release. It is possibile to select the socket implementation (new or old in that case ) ?

**Comment by jarrodek** [comment] 2016-05-13 20:50
Not really @glfp . In apps environment XHR don't work as well. 
However I just released a complementary extension for ARC (https://chrome.google.com/webstore/detail/arc-cookie-exchange/apcedakaoficjlofohhcmkkljehnmebp) that I can use not only for cookies sync but also for proxying XHR data. That could fix the issue here.

**Comment by jarrodek** [comment] 2016-05-16 21:25
Glad to post it: it's fixed by https://github.com/jarrodek/ChromeRestClient/commit/89973b258fe80f0bcc33814111917d6ef272617c

**Closed by jarrodek** 2016-05-16 21:25 UTC

**Comment by sawilde** [comment] 2016-05-17 03:07
Are you saying I will not have issues once I take the latest ARC?

**Comment by jarrodek** [comment] 2016-05-17 18:17
In [beta channel](https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel) at least. I'll release this update to stable version in coming days when it will be tested.
