### ISSUE TITLE
Unabled to Upload File

### ISSUE THREAD

**Issue by romulogp** [jarrodek/ChromeRestClient#981] opened 2017-03-17 17:33 UTC
I've been trying to upload a file to api endpoint.

## Expected outcome
Filed uploaded successfully.

## Actual outcome
When using **Content-Type: multipart/form-data** i face and Internal Server Error:
{
"timestamp": 1489771142292,
"status": 500,
"error": "Internal Server Error",
"exception": "org.springframework.web.multipart.MultipartException",
"message": "Could not parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",
"path": "/api/v1/invoices/upload"
}

And using **Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW** i face this error:
{
"status": 400,
"error": "Bad Request",
"exception": "org.springframework.web.multipart.support.MissingServletRequestPartException",
"message": "Required request part 'file' is not present",
"path": "/api/v1/invoices/upload"
}
**PS.:** That boundary value i've got from PostMan POST Request, which works great. if wasnt that, i could not even exit the Internal Server Error.
## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (10)

## Steps to reproduce
1. Select and add a file from System.
2. Make a POST request using Content-Types mentioned above.

**Comment by KazukiMorozumi** [comment] 2017-04-06 05:38
I have faced same issue.

### input on RestClient
Here is request data.
![image](https://cloud.githubusercontent.com/assets/19401388/24739046/d1116274-1ad4-11e7-880d-40c8c1b2a726.png)

### server side log
Server log said, no data is sended.
> Caused by: org.apache.commons.fileupload.FileUploadException: the request was rejected because no multipart boundary was found
> 	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:990)
> 	at org.apache.commons.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:310)
> 	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:334)
> 	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:115)
> 	at org.springframework.web.multipart.commons.CommonsMultipartResolver.parseRequest(CommonsMultipartResolver.java:158)
> 	... 40 more
> 

### packet capture
Also, packet capture with wireshark shows there is no file in http request.
![image](https://cloud.githubusercontent.com/assets/19401388/24739133/61278e60-1ad5-11e7-88b1-ae0f3c983ef9.png)

## Environment
App: 9.14.64.305-stable
Chrome: 57.0.2987.133
OS: Mac El Capitan (10.11.6)

**Comment by jarrodek** [comment] 2017-04-07 11:55
Hi,

This is duplicate of the #945
Because it's a huge bug (in Chrome this time, not the app) that affects core of the application I'm still working on it.

I'm closing as a duplicate but subscribe to referenced bug for updates.

**Closed by jarrodek** 2017-04-07 11:55 UTC
