### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by tedhenkels** [jarrodek/ChromeRestClient#449] opened 2016-04-08 21:56 UTC
Your description here
trying to make http request

## Expected outcome
What should happen?
http request should go through successfully  

## Actual outcome
What happened?
get the message in the title 

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.110
Platform: Mac OS X (10_11_3)

## Steps to reproduce
1. make request
2. get error response
3.

**Comment by jarrodek** [comment] 2016-04-09 13:37
Duplicate of #432

**Closed by jarrodek** 2016-04-09 13:37 UTC
