### ISSUE TITLE
History on ARC wrong

### ISSUE THREAD

**Issue by ishant-barnwal** [jarrodek/ChromeRestClient#896] opened 2016-11-16 10:24 UTC
Your description here

## Expected outcome
Previously, a request per end point used to be logged here.

## Actual outcome
Only the last end point used for the day is logged.

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.99
Platform: Windows (7)

**Comment by jarrodek** [comment] 2016-11-21 17:17
The history now works as it was designed earlier but for some reasons it was displaying all the requests made by the app. 

Now, if the request has been already made the same day (from midnight to midnight) it is not added as a new history item but timestamp of the request is changing (so it can be displayed on top of the list). Two requests are equal when the URL (without query params) and method matches. 
It does not check for the headers and payload because it is still the same endpoint and method and as a history item it should only show it once.

As per this explanation I'd be inclined to close this as WAI.

**Comment by dunght160387** [comment] 2016-11-29 03:49
Yes, please do not publish new release version if it can not work properly when testing.

Thanks.

**Comment by jarrodek** [comment] 2016-11-30 01:13
I don't understand @dunght160387 I'm not sure if you meant to post in this thread.

**Closed by jarrodek** 2016-11-30 01:13 UTC
Labels: WAI
