### ISSUE TITLE
unicode character not shown correct in response

### ISSUE THREAD

**Issue by abmahmoodi** [jarrodek/ChromeRestClient#1079] opened 2017-10-16 20:07 UTC
when I run an API, unicode character not shown correct in response .
## Expected outcome
unicode character shown correctly.

## Actual outcome
{
"response": 0,
"error": "Ø¹ÙÙÛØ§Øª Ø¨Ø§ ÙÙÙÙÛØª Ø§ÙØ¬Ø§Ù Ø´Ø¯."
}

## Versions
App: 10.0.3
Platform: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by jarrodek** [comment] 2017-10-16 20:46
Hi,
This is a duplicate of #1074.
It is fixed in 10.0.4 (already published).

**Closed by jarrodek** 2017-10-16 20:46 UTC
