### ISSUE TITLE
Suggestion dropdown is not working

### ISSUE THREAD

**Issue by Arunagnz** [jarrodek/ChromeRestClient#360] opened 2016-01-14 09:01 UTC
Previously, Rest client gave suggestion from the history. Now it is absent. This is very useful feature and expected one too. This issue found only after 1/12/2016 update.

**Comment by jarrodek** [comment] 2016-01-14 12:56
Which version of Chrome and the app do you have?
App version 4.4 and 4.5 I tested for Chrome >= 45 and it is working. For me at least. Besides, this module hasn't changed for years. Can you see any error in console? And finally do you have history enabled?

**Comment by Arunagnz** [comment] 2016-01-19 10:53
I am using chrome Version 47.0.2526.111 m and rest client Application version: 4.5.0
Stable. I haven't seen any errors in console. Suggestion from history alone not working, Can't get your question: "do you have history enabled?".

**Comment by Arunagnz** [comment] 2016-01-19 11:07
The update removed the content type dropdown - I do not want to type this to save it, please bring back the dropdown. it makes this app not productive.as before.

Older version is simple and ease of use.

**Comment by jarrodek** [comment] 2016-01-19 12:49
Lets focus on one issue here. 
So additional question - is this always not working or with some particular query? I still can't reproduce the problem on the browser you have. Maybe there is some particular case.

Also, can you try run this code in the console?
```javascript
chrome.history.search({text: 'http://', maxResults: 10}, function(res){ 
  console.log(res); 
});
```
It should print 10 matches. If there is some output it means that the API is working.

As for the encoding dopdown please refer to my blog post: http://restforchrome.blogspot.co.uk/2016/01/encoding-drop-down-removal-from-app.html

**Comment by Arunagnz** [comment] 2016-01-20 05:01
My problem is, Rest client suggest me the URL in dropdown from chrome(Browser) history not from the rest client history?

@jarrodek : Do you have any solution for that?

**Comment by jarrodek** [comment] 2016-01-20 16:07
Because it's design to take history entries from both this sources: internal app storage and chrome history API. There is an algorithm that is ordering the results by best match and it don't care if it is from chrome.history API or internal storage.
This behaviour will change in the future and there will be no calls to the chrome.history API. It's not however issue related but rather platform architecture related. 
So I'm closing this issue now since the change is inevitable on next release.

**Closed by jarrodek** 2016-01-20 16:07 UTC
