### ISSUE TITLE
seriously, you removed the ability to search?

### ISSUE THREAD

**Issue by g--brown** [jarrodek/ChromeRestClient#481] opened 2016-04-14 21:16 UTC
I used to be able to just click a normal browser ctl-f and search the page for content.  Now, that's no longer there (at least I cant find it)

## Expected outcome
CRL-F Should allow me to search

## Actual outcome
bupcus

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.112
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. you get it.
2. 
3.

**Comment by jarrodek** [comment] 2016-04-15 09:22
I haven't actually removed it because it need to be implemented in apps. Previous version used Chrome search bar. However I'm working on search in the `search` branch.

And duplicate of #429

**Closed by jarrodek** 2016-04-15 09:22 UTC
