### ISSUE TITLE
Response display "Abort / timeout" message

### ISSUE THREAD

**Issue by suraj18** [jarrodek/ChromeRestClient#559] opened 2016-04-20 11:34 UTC
Hi,
I m using latest version of RestClient, it shows timeout response when request is processing at server side.

## Expected outcome
It should be wait till response come.or let me if there is any setting at client to wait till response come.

## Actual outcome
What happened?

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-04-20 12:01
Duplicate of #502

**Closed by jarrodek** 2016-04-20 12:01 UTC
