### ISSUE TITLE
Can't paste in Chrome (Mac OS)

### ISSUE THREAD

**Issue by hhuynh** [jarrodek/ChromeRestClient#710] opened 2016-06-17 16:09 UTC
Your description here
If you have something in clipboard, pasting it using Cmd V won't work. I have to right click and choose Paste from context menu.

## Expected outcome
What should happen?
Pasting with keyboard should work

## Actual outcome
What happened?
Nothing pasted

## Versions
App: 7.20.37.203-stable
Chrome: 51.0.2704.84
Platform: Mac OS X (10_11_5)

## Steps to reproduce
1. copy something to clipboard
2. go to CRC and try pasting it into any of text boxes with Cmd + V
3. nothing happens.
4. pasting using right click context menu, however, will work

**Comment by jarrodek** [comment] 2016-06-20 10:04
Hi,

Thank you for an issue report.
I can't reproduce the problem. Either it's platform specific or you have system handlers that prevent cmd + V command from execution.
Anyway it doesn't look like an issue with the app. I tried it on mac and it is working as it should. If you think it is platform related you should contact Chrome team (crbug.com).

I'd be inclined to close this issue report as invalid.

**Closed** 2016-07-19 13:18 UTC
Labels: awaiting-response, invalid
