### ISSUE TITLE
Client doesn't send payload from corresponding input. Previous request payload is sent

### ISSUE THREAD

**Issue by yaroslav-kovalchyk** [jarrodek/ChromeRestClient#367] opened 2016-01-19 09:08 UTC
Steps:
1) Send PUT request with some payload
2) Change method to GET and execute some request (this step may be redundant, but I'm describing my experience)
3) Change method to PUT and enter another value to payload input
4) Execute PUT request and check, that payload of first PUT request is sent
Expected: new payload is sent

**Comment by getmeben** [comment] 2016-01-20 11:29
This unfortunately renders this awesome app unusable. It doesn't send what you have on screen when you press send. I am sadly looking for an alternative.

You don't even need to change http verb. Just try changing the request body and what you have in the input field is not sent in the http call.

**Comment by getmeben** [comment] 2016-01-20 11:36
Can I suggest you roll-back the live version of the chrome web app now while you fix these problems please? Otherwise you're going to lose all of your users.

**Comment by yaroslav-kovalchyk** [comment] 2016-01-20 11:39
+1 for roll-back. I'm already using postman. Current version of restClient disallow any usage.

**Comment by getmeben** [comment] 2016-01-20 12:16
Am also moving to postman...

**Comment by jarrodek** [comment] 2016-01-20 16:16
Hi, thanks for an issue report.
Can you send me app and Chrome version numbers? Do you use "raw" or "Form field"? Do you have CodeMirror enabled in settings? I can't reproduce the problem it on stable and dev channel. It seems to work as designed.

**Comment by braddewitt** [comment] 2016-01-20 20:43
Since the upgrade, I consistently see this issue as well.  
- I use the "raw" field.
- I have not changed the CodeMirror setting - it appears to be On by default.
- Application version: 4.6.0 Stable
- Chrome for OS X - Version 47.0.2526.106 (64-bit)

**Comment by craiggoudy** [comment] 2016-01-20 22:31
I sadly am in the same boat...I have the exact same setup as braddewitt...I lost 3 hours today just assuming that my authorization token was wrong when in fact it was the app sending the wrong (old) token...makes me sad as I love this app....but have switched to Postman (for now...if there is a quick fix I will return)

**Comment by jarrodek** [comment] 2016-01-21 02:06
And additional question, if you switch off code mirror is it starts working?
I'm just trying to limit the places where I should look for a bug.

**Comment by craiggoudy** [comment] 2016-01-21 16:03
I just switched off code mirror and I am seeing the same behaviour...hope that helps....good luck finding the bug

**Comment by getmeben** [comment] 2016-01-21 17:59
Hey Paweł, Sorry for the delay in replying. I'm on mac chrome 48.0.2564.82 (64-bit), app is 4.6.0 stable, I always use raw, and codemirror is ON. Aha! I hadn't thought of trying with the code mirror off, but with it off, things are back to normal and working fine :) This not only fixes this bug here (not passing through what's in the request body), but also the other bug I commented on re the header value being truncated with anything after a ; - hope this helps to track down the source, there's a good suspect now!

**Comment by jarrodek** [comment] 2016-01-21 18:13
Thanks for the comment. I'll take care of it tomorrow. Today is getting late...

**Comment by craiggoudy** [comment] 2016-01-21 18:32
After seeing getmeben's comment I tried it a second time with Code Mirror off and I was mistaken...my request DID work.

**Comment by jarrodek** [comment] 2016-01-21 19:33
Thanks for clarifying @craiggoudy this. I'll fix it tomorrow during the day (London's time).

**Comment by jarrodek** [comment] 2016-01-22 11:40
I think it may be related to #368

**Comment by jarrodek** [comment] 2016-01-22 11:41
And #365

**Closed** 2016-01-25 21:48 UTC
Labels: bug
