### ISSUE TITLE
Posting a file doesn't work

### ISSUE THREAD

**Issue by mdkitzman** [jarrodek/ChromeRestClient#990] opened 2017-04-03 15:58 UTC
Selecting POST, and posting a file to a server.

Clicking on the "Files" tab and add any file and give it a name.  Sending the request does not send the file contents as a multipart-form request, and does not send the file data.

## Expected outcome
A post should be created, similar to a form post, as a multipart-form request with the file information attached.

## Actual outcome
Here is how I have set up the request.
![capture](https://cloud.githubusercontent.com/assets/11448209/24618366/116f7d48-1854-11e7-8e15-341695bb51b5.PNG)
Here is what was sent (captured using Wireshark)
```
POST /api/import HTTP/1.1
HOST: 10.16.21.165
accept: application/json
content-length: 0
```
The "content-type" header was not added as it says it would, and the content length is 0, and there is no file information being sent

## Versions
App: 9.14.64.305-stable
Chrome: 57.0.2987.133
Platform: Windows (10)

## Steps to reproduce
1. Select POST
2. Click on the Files tab and add a file
3. No file is sent in a post

**Comment by mdkitzman** [comment] 2017-04-03 17:15
Probably related to #981

**Comment by jarrodek** [comment] 2017-04-07 11:54
Hi,

This is actually duplicate of the #945
Because it's a huge bug (in Chrome this time, not the app) that affects core of the application I'm still working on it.

I'm closing as a duplicate but subscribe to referenced bug for updates.

**Closed by jarrodek** 2017-04-07 11:54 UTC
