### ISSUE TITLE
Scroll bar is hidden behind the top panel

### ISSUE THREAD

**Issue by atishagrawaljss** [jarrodek/ChromeRestClient#561] opened 2016-04-20 14:05 UTC
Your description here

I made a POST call to an API and got some data. I am unable to see a scrollbar so that I can click and drag it to the bottom to reveal the response.

## Expected outcome
What should happen?

I must see clearly a scroll bar to be able to pull down

## Actual outcome
What happened?

The scrollbar was hidden behind the top panel

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. make any valid API call
2. wait for the response.
3. check on the top-right corner. You won't be able to see the scrollbar head
![arc bug](https://cloud.githubusercontent.com/assets/17405799/14677373/0ec474d6-072f-11e6-915c-1a85bb413b51.png)

**Comment by jarrodek** [comment] 2016-04-20 14:51
Hi,

Thank you for an issue report.
I can't reproduce it now but later I'll try to do it on Windows. Anyway it will be Polymer's scroll-panel issue so I'll try to either fix it or find a workaround.

**Comment by jarrodek** [comment] 2016-04-28 16:06
I can confirm that this is Polymer's [paper-scroll-header-panel](https://github.com/PolymerElements/paper-scroll-header-panel) issue. In examples in this element's demo pages there is the same issue.
I can only fix it when the element is fixed.

**Comment by jarrodek** [comment] 2016-05-09 19:05
As per my previous comment I'm closing this issue. There's nothing I can/should do.

**Closed by jarrodek** 2016-05-09 19:05 UTC
Labels: bug, Component: Response panel

**Comment by madeng** [comment] 2017-04-28 15:15
There was a discussion in 2015 about this. They say to migrate to [app-layout](https://github.com/PolymerLabs/app-layout).

https://github.com/PolymerElements/paper-scroll-header-panel/issues/28
