### ISSUE TITLE
Request timeout is to small

### ISSUE THREAD

**Issue by Mart-Bogdan** [jarrodek/ChromeRestClient#541] opened 2016-04-19 19:19 UTC
I'm debugging my API server with breakpoints, and your app is complaining 
```
Abort / timeout

The request has been aborted manually or because of the conection timeout. There were no response from the server but the connection wasn't closed.

```

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (10)

**Comment by jarrodek** [comment] 2016-04-20 11:05
Duplicate of #502

**Closed by jarrodek** 2016-04-20 11:05 UTC
