### ISSUE TITLE
get method should allow for body

### ISSUE THREAD

**Issue by kgignatyev** [jarrodek/ChromeRestClient#942] opened 2017-01-26 01:35 UTC
Your description here

REst client should allow sending body with GET request. Is is valid according to the new specks  and widely used in ElasticSearch 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html

## Expected outcome
What should happen?

selecting GET method should allow BODY raw

## Actual outcome
What happened?

## Versions
App: 8.19.60.296-stable
Chrome: 56.0.2924.76
Platform: Mac OS X (10_11_6)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2017-01-27 14:21
This is duplicate of #22 and #319

The spec do not allow payloads in the GET request. Therefore you can't expect clients to allow this. The service you referred directly breaks the HTTP spec asking users to make such request (which in many cases won't work).

Other browser implementations of the HTTP transport (XHR and Fetch) do not allow sending data with GET request. XHR will just ignore the payload and send the rest of the message (you can observe this in network panel when sending GET with body) and Fetch will throw error when trying to set a body on `GET` request:

> TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

I can only suggest you to file an issue report on the service provider's issue tracer and suggest them to comply with the spec.

I'm closing this issue as wont fix.

**Closed by jarrodek** 2017-01-27 14:21 UTC

**Comment by kgignatyev** [comment] 2017-01-27 18:04
RFC7231 does NOT prohibit body
https://tools.ietf.org/html/rfc7231#section-4.3.1

even rfc2616  explicitly permits CLIENTs to send body with all but HEAD request 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3
and recommends that _SERVERS_ ignore body.

In other words both specs do NOT prohibit clients to send body with requests. 
So, I suggest you to reconsider and improve usability of the tool because major software package supports body in GET-s.

Also, apache http client changed its implementation from not allowing to allowing body with GET requests since v5 to comply with 7231
https://issues.apache.org/jira/browse/HTTPCLIENT-1703

Ideally there should be 'VIEW' request that would allow body but its semantics state must not modify server state and ELK should support that, but ....

Regards

**Comment by jarrodek** [comment] 2017-01-27 20:02
Hi,

Thank you for good argument.

1) explicitly does not prohibit but also does not explicitly allows it. In fact it doesn't mention the body in the request.

2) It does not explicitly allows body in every request. It defines what is the message body and that the spec for the method may explicitly prohibit it but there's nowhere mentioned that the http request must have message body. (note that the glossary for W3 specs defines concepts like MUST, SHOULD, MAY etc).

The decision is still the same. ARC can't behave differently than other HTTP clients (even if it works directly on socket and don't really care what other clients do). Allowing this in ARC may be confusing for others who may base API design on ARC's capabilities. After moving the API to production it will become clear that majority of HTTP clients does not allows this behaviour and the API must be changed.

I understand what you are saying but I can't arbitrary choose how the client will work without considering environment which is other HTTP clients (they are not considering GET as a method that carries message body). This change most probably produce more problems than benefits.

**Comment by kgignatyev** [comment] 2017-01-27 20:28
1. Per RFC7231:  "A server SHOULD read and forward a message-body on any request" IMO explicitly allows clients to send body with any request.
2. I understand possible confusion and prevalent use of GET methods.
3. Still think that to be useful and correct client should allow body when '**custom**' method is chosen and method name set to '**get**', currently it does not allow custom method name to be 'get' which I would argue is not good 'custom' behavior
4. "other" clients allow get body at user level, for example **curl**  sends it happily
curl -X GET -H "Content-type: application/json" -H "Accept: application/json"  --data-raw '{"query" : {"term": { "rr1" : "aaaa"}}}' http://127.0.0.1:9200/_search

Response:
{"took":5,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":1.287682,"hits":[{"_index":"archimedes","_type":"asset","_id":"test-obj.mp4","_score":1.287682,"_source":{"cc":{"a":"aaaa","b":"bbb"},"rr1":"aaaa","rr2":"bbb"}}]}}

**Comment by jarrodek** [comment] 2017-01-27 20:38
Hi,

I don't want to argue about meaning of the spec. However, if the spec says something what server should or should not do not see any reason to apply it to clients.
If cURL have it implemented - bless them. XHR and Fetch don't and this is my baseline. ARC can't work differently than two other mostly distributed HTTP transport implementations (in every browser).

There is a consensus about this issue around web developers and I really don't see any reason to take an action here.
