### ISSUE TITLE
History Tab

### ISSUE THREAD

**Issue by jasnajayaraj** [jarrodek/ChromeRestClient#379] opened 2016-02-09 04:31 UTC
In 4.11 noticed that the recently send request is being added at the end in the history rather than at the begining of the history as used to be before.

**Comment by jarrodek** [comment] 2016-02-09 09:16
Duplicate of #378

**Closed** 2016-02-09 19:48 UTC

**Comment by jasnajayaraj** [comment] 2016-02-10 05:33
Thank you
