### ISSUE TITLE
HTTP Post Not Passing Authentication

### ISSUE THREAD

**Issue by mrgadget** [jarrodek/ChromeRestClient#472] opened 2016-04-12 22:47 UTC
My client has just been upgraded to the new version and I've tried to use a saved request that previously worked in the old client (about 10 minutes ago before it was upgraded).

## Expected outcome
Request should authenticate with Windows credentials (as per previous client)

## Actual outcome
Received a 401.3 Unauthorized error from web service

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Windows (8.1)

## Steps to reproduce
1. Perform a HTTP post (or possibly any HTTP action) to a server requiring NTLM/Integrated authentication.

**Comment by jarrodek** [comment] 2016-04-15 10:15
I'm not sure what's the reason for issue here. Is that the authorization header is not passed to the server?  Or it is about not using chrome's session state?

**Comment by mrgadget** [comment] 2016-04-15 10:25
I would say the authorization header isn't being passed.  The session
state shouldn't be required as we are using integrated authentication
(meaning windows credentials are being passed to the server by the
browser).  As per the bug this worked fine prior to the upgrade.
 
Happy to get any logs or traces that may help.
 
On Fri, 15 Apr 2016, at 10:15 PM, Paweł Psztyć wrote:
> I'm not sure what's the reason for issue here. Is that the
> authorization header is not passed to the server?  Or it is about not
> using chrome's session state?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/jarrodek/ChromeRestClient/issues/472#issuecomment-210402571

**Comment by jarrodek** [comment] 2016-04-15 10:55
I'm afraid that the issue is caused by this passing a credentials by the browser.
Chrome apps are separated from Chrome and they are not sharing session state (and credentials).
Without changing overall transport architecture I can't do much.
I will however look into this but I don't think it will be done very quickly since it's a lot of designing and coding. Not sure if it will get into the next update.

**Comment by mrgadget** [comment] 2016-04-15 11:04
But was the previous version not a Chrome app? The version that ran
within a chrome window.  It worked fine in there.  Is there any way to
get the old version back?
 
 
On Fri, 15 Apr 2016, at 10:55 PM, Paweł Psztyć wrote:
> I'm afraid that the issue is caused by this passing a credentials by
> the browser.
>  Chrome apps are separated from Chrome and they are not sharing
>  session state (and credentials).
>  Without changing overall transport architecture I can't do much.
>  I will however look into this but I don't think it will be done very
>  quickly since it's a lot of designing and coding. Not sure if it will
>  get into the next update.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/jarrodek/ChromeRestClient/issues/472#issuecomment-210414116

**Comment by jarrodek** [comment] 2016-04-15 13:51
Not really Chrome app as what we now call Chrome app. Right now the old app would be called legacy app. It was something between apps and extensions. It was working in Chrome window and shared network settings. It is not the case right now. 

It might be possible to makes it work again by creating a sandboxed iframe that will make an XHR request. But I'm not sure right now if it work because such frames do not have the same level of permissions as the app so CORS limitations may apply. 
I need to investigate it.

**Comment by mrgadget** [comment] 2016-04-15 20:01
Ah I see then. Thanks for the explanation.
 
Would it be possible to re-publish the old version with the likes of
'legacy' appended to the name or something?
 
It's been a fantastic tool for debugging web services but as mine all
involve Windows authentication it's now of no use to me :(
 
 
On Sat, 16 Apr 2016, at 01:51 AM, Paweł Psztyć wrote:
> Not really Chrome app as what we now call Chrome app. Right now the
> old app would be called legacy app. It was something between apps and
> extensions. It was working in Chrome window and shared network
> settings. It is not the case right now.
> It might be possible to makes it work again by creating a sandboxed
> iframe that will make an XHR request. But I'm not sure right now if it
> work because such frames do not have the same level of permissions as
> the app so CORS limitations may apply.
>  I need to investigate it.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/jarrodek/ChromeRestClient/issues/472#issuecomment-210471398

**Comment by mgpcoe** [comment] 2016-04-18 14:46
+1 on this whole thread. I've been using ARC for a couple of years now to develop REST APIs, and one of them uses Basic auth. Since the forced upgrade, it doesn't even ask for authentication, which means I can't test anything through these APIs... which in turn makes this app entirely useless.

**Comment by jarrodek** [comment] 2016-04-18 14:49
@mgpcoe Basic auth is supported by the app. It's just a simple header set with the request and there's nothing left to do in that matter. You even have  auth challenge when the response's status code is 401 and the server require the basic authentication. More over the app is storing login and password internally so you don't need to enter it all over again.

**Comment by mgpcoe** [comment] 2016-04-18 14:58
So I have to manually craft my basic auth header? This used to be a form that popped up (granted, it was part of the Chrome UI). Seems like a pretty basic piece of UI that got missed. Right now I'm making my request against a Basic auth API, and it just flatly gets rejected, HTTP 401, with no opportunity to provide the requested credentials.

**Comment by jarrodek** [comment] 2016-04-18 15:03
You should see a dialog like this:
![image](https://cloud.githubusercontent.com/assets/3320020/14608700/aff93218-057e-11e6-8d4f-081127935498.png)

This is basically the same as Chrome's auth dialog.

Other way is to use a dialog in headers form that helps you encode the header value:
![image](https://cloud.githubusercontent.com/assets/3320020/14608737/d87e0dd0-057e-11e6-9f0a-888a6804432b.png)
![image](https://cloud.githubusercontent.com/assets/3320020/14608803/0ffe0198-057f-11e6-8a0d-e1657942dee3.png)

You can open the dialog clicking on a pencil in the editor.

**Comment by mgpcoe** [comment] 2016-04-18 15:10
I'm running 7.7.26.168, same as the Chrome Web Store says is the latest available, against Chrome 49.0.2623.112 on OS X. The first dialog you mention never pops up. The second, yeah, I can find, but buried that deep, and having to reach out and ask the maintainer for help, is a poor user experience. By comparison, Postman offers Authorization as a separate tab on the request form. Much more straightforward.

FWIW, I used to recommend ARC over Postman to my fellow developers. You've fallen behind your competition.

**Comment by jarrodek** [comment] 2016-04-18 15:16
@mgpcoe What is exact value for the `Www-Authenticate` header in response to this 401?

**Comment by jarrodek** [comment] 2016-04-18 21:51
The same as #487

**Comment by mjd327** [comment] 2016-04-21 16:41
The authentication popup is not coming up for us either. Www-Authenticate is of the form  'OAuth realm="[realm]"; Basic realm="[realm]" '

So maybe it is failing to parse that?

**Comment by mjd327** [comment] 2016-04-21 16:53
Also there seems to be a minor bug where the pencil to bring up the authentication form doesnt come up again if you delete that header and try to re-add it (unless you switch tabs back and forth)

**Comment by jarrodek** [comment] 2016-05-04 22:54
@mjd327 OAuth is not yet supported by the app. It's still to be designed and implemented so it can be useful.
As for a login and password prompt, it reacts if the `www-Authenticate` header contains `basic` word in it. Realm is not taken into consideration in this case.

Thanks for a report on not adding editor to the previously removed header. It will be fixed.

**Closed** 2016-05-09 18:49 UTC
Labels: bug
