### ISSUE TITLE
Authorization headers not being sent?

### ISSUE THREAD

**Issue by fluffynuts** [jarrodek/ChromeRestClient#460] opened 2016-04-11 15:15 UTC
After the latest update, it seems that my Authorization headers aren't being sent. I have to manually specify the value "Basic {apikey}" because that's all the information I have -- I don't have a username / password. This used to work, but now the service returns a 400 / bad request with the message that my REST API key is missing. I can query with curl though.

## Expected outcome
I should get REST query results, like I used to.

## Actual outcome
I get no results and an error from the service.

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Windows (10)

## Steps to reproduce
1. Use REST service with Authorization requirement where you have to input the Authorization header value manually
2. Attempt query with manually-entered Authorization header
3. Fail. Cry. Be confused.

**Comment by jarrodek** [comment] 2016-04-11 15:18
Duplicate of #453

**Closed by jarrodek** 2016-04-11 15:18 UTC
