### ISSUE TITLE
it is not support the Host header

### ISSUE THREAD

**Issue by SimonShia** [jarrodek/ChromeRestClient#771] opened 2016-08-26 10:05 UTC
Source message has two HOST headers,one is i added,and anther is fom the url
![image](https://cloud.githubusercontent.com/assets/6753531/18001822/4a974a8c-6bb7-11e6-9764-1baa0eac6bea.png)

**Comment by jarrodek** [comment] 2016-08-26 11:37
Hi,

Thank you for issue report. 
Basically you shouldn't use `host` header at all. It should be set by transport and taken from the URL you provide. Otherwise the URL wouldn't be necessary. 

Even if it works as intended I'll label it as a bug because the app shouldn't allow you to set host header and this should be fixed.

**Comment by jarrodek** [comment] 2016-09-12 11:48
It is fixed in https://github.com/jarrodek/ChromeRestClient/commit/949aa57b4a5324bb73869a530d48ad50d1dea86b

**Closed by jarrodek** 2016-09-12 11:48 UTC
Labels: bug
