### ISSUE TITLE
ARC upgrade error

### ISSUE THREAD

**Issue by mskcode** [jarrodek/ChromeRestClient#876] opened 2016-11-09 07:45 UTC
So ARC decided to erase all the saved queries during upgrade and now I have nothing...

Anyway, here's the error logs:

The app errored during latest upgrade.

## Logs

```
Initializing upgrade
[1016] Checking if upgrade is required.
[1016] Deleting new databases if exists.
Maximum IPC message size exceeded.
UnknownError: Maximum IPC message size exceeded.
```
## Versions
App: 8.6.52.275-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_11_6)

**Comment by jarrodek** [comment] 2016-11-09 13:27
Hi, Thank you for the issue report. The fix has been released and the update is waiting in Chrome Store (version >= 8.9).

It's not deleting any data. All data are in the app and are safe. Also, the app will attempt to upgrade next time when you run it.

And I'm closing it as a duplicate of #830. But thank you again for the report.

**Closed by jarrodek** 2016-11-09 13:27 UTC
