### ISSUE TITLE
Respond with emty BODY and status=200 deadlock break next requests.

### ISSUE THREAD

**Issue by SRyabinin** [jarrodek/ChromeRestClient#891] opened 2016-11-14 10:54 UTC
I POST request two times.
http://localhost/cgi/xxx.cgi?req=api&origreq=auth&op=add
Content-Type: application/x-www-form-urlencoded
accept: */*
user-agent: SomeCustomAgent

FormData: login=user&fio=Luke&password=user&complect=LAW&email=1@1.ru&profile=XXX

 First request returns 200 and emty BODY (my server does not return content for this type of requests). I post second request and nothing happens.

If the same request returns 403: and some data in BODY next requets works properly. So the problem is in emty body.

## Expected outcome
Server receives second request.
Second request will respond 200 and emty BODY too,

## Actual outcome
Server does not receive second request.
Cancel request from ARC and repeat again does not resolve sending problem.
## Versions
App: 8.9.53.279-stable
Chrome: 54.0.2840.71
Platform: Windows (7)

## Steps to reproduce
1. Post request first time and get response 200 with emty body.
2. Try to post request second (and more) time.
3. Restart ARC to manage it works.

**Comment by jarrodek** [comment] 2016-11-14 15:18
Hi,

Thank you for very detailed issue report. I'm already on it and it's a duplicate of #887
It seems to be an issue with the database library used with the app. I'll update the app very soon.
Meanwhile I'll close this issue to have only one opened on this matter.

**Closed by jarrodek** 2016-11-14 15:18 UTC
