### ISSUE TITLE
Not end process after PATCH

### ISSUE THREAD

**Issue by dunght160387** [jarrodek/ChromeRestClient#740] opened 2016-08-05 04:06 UTC
The process is not ended after PATCH successfully.

## Expected outcome
The process is ended after PATCH successfully.

## Actual outcome
The process is NOT ended after PATCH successfully.

## Versions
App: 7.26.44.220-stable
Chrome: 47.0.2526.106
Platform: Linux (-)

## Steps to reproduce
1. Do Patch (successful)
2. See process is running
3. Manually end by hand!!!

**Comment by dunght160387** [comment] 2016-08-05 04:07
I like old ARC tool on web, easy to use and get no bug.

**Comment by dunght160387** [comment] 2016-08-05 04:13
Also more detail: 

```
I made a normal PATCH request, then server (my own api server) returned http response with code 204.
Is there any wrong things here???
```

Rgds.

**Comment by jarrodek** [comment] 2016-08-08 18:40
This is duplicate of #698

**Closed by jarrodek** 2016-08-08 18:40 UTC
