### ISSUE TITLE
History view headers are not resizable

### ISSUE THREAD

**Issue by anealkidcheckcom** [jarrodek/ChromeRestClient#604] opened 2016-04-22 21:39 UTC
Your description here
The headers in the history view are not resizable, and instead autosize. I feel the default percentages are a little too whitepace intensive, but that would be fine if they were resizable.
When the entire window is medium sized (1024x768) the checkbox, "Time", "Method", and "Action" columns show a bunch of white space, while the URL column is only showing 1/2 my URL string.
Since I would guess a lot of people use this tool for testing REST endpoints, the short URL string makes it difficult to determine what endpoint was hit.  At a reasonable size you get the transport, machine name, port, and the application's base URL (which would be the same for all your REST resources), but not the more specific part of the URL.

## Expected outcome
What should happen?
The headers should be resizable at a minimum, but it would be nice if the columns with fixed data had a fixed width and not so much white space

## Actual outcome
What happened?
see description

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.87
Platform: Linux (-)

## Steps to reproduce
1. Do a request to a URL that's medium long (http://www.microsoft.com/hardware/en-us/downloads) for example
2. View history
3. Notice that you can't see the whole URL unless your window is fairly big

**Comment by jarrodek** [comment] 2016-04-23 21:31
Hi,

Thank you for issue report.
This is actually a duplicate of #500. 

Please, refer to this issue report for further notification.
As per duplicate I'm closing this issue.

**Closed by jarrodek** 2016-04-23 21:31 UTC
