### ISSUE TITLE
Hate the move to a home app

### ISSUE THREAD

**Issue by RickRockhold** [jarrodek/ChromeRestClient#464] opened 2016-04-11 17:11 UTC
By leaving the browser behind, you also leave behind features that the browser implemented. For example, while operating in the browser, I could use the browser's "Find" feature to search the response. In the app, I can't. (Other features, like form input autocomplete, are also MIA) Please bring back the browser interface!

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-04-11 17:19
Duplicate of the #462

**Closed by jarrodek** 2016-04-11 17:19 UTC
