### ISSUE TITLE
Response is not shown in Advance rest client

### ISSUE THREAD

**Issue by raghuhck** [jarrodek/ChromeRestClient#581] opened 2016-04-21 06:30 UTC
I am doing post request with 2 params which does business processing and response will returned back to client.
## Expected outcome

Response should be shown in Advance rest client
## Actual outcome

Call to web service is showing as in progress for long time.No response is shown 
## Versions

App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)
## Steps to reproduce
1. Do a post request with 2 parameters of long string and returns response as string
2. 
3.

**Comment by CodeHarmony64** [comment] 2016-04-21 06:50
I am also facing the same issue. Even with the get it keep running and running , I don't get any response neither any error. :(

**Comment by jarrodek** [comment] 2016-04-21 14:51
Hi,
Thank you for issue report.

I believe it is a duplicate of #580. Probably logs can confirm that.
Anyway the fix is tested now so it should get working in coming days.

**Comment by jarrodek** [comment] 2017-10-13 22:44
Closing because of lack of activity

**Closed by jarrodek** 2017-10-13 22:44 UTC
