### ISSUE TITLE
 偶尔出现崩溃，会出现发不了请求

### ISSUE THREAD

**Issue by psyuhen** [jarrodek/ChromeRestClient#895] opened 2016-11-16 08:17 UTC
Your description here

## Expected outcome
What should happen?

偶尔出现崩溃，会出现发不了请求

## Actual outcome
What happened?

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.99
Platform: Windows (10)

## Steps to reproduce
1. open
2. input body
3.  send

**Comment by jarrodek** [comment] 2016-11-28 14:12
Hi, 
Can you be more specific on this? What is happening exactly? Is there any error in logs (they are in the left navigation)? It is happening always or for specific request?

I'll be glad for more details :)

**Comment by psyuhen** [comment] 2016-12-03 11:25
Error during fetch. Request aborted

Error: Request aborted
    at SocketFetch.abort (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:34196:30)
    at _timeout.timeoutId.window.setTimeout (chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/elements/elements.js:34319:14)

**Comment by jarrodek** [comment] 2017-01-17 19:13
Request aborted error happens then you actually abort the request using the abort button. Are you clicking the `send` button twice? It is instantly replaced by the `abort` button and if you clicking it twice you are aborting the request.

I can't see any other explanation since this is the only way to cause this error.
Also I'm not able to reproduce this.
I'm closing it as Work As Intended but feel free to reopen this issue if needed.

**Closed by jarrodek** 2017-01-17 19:13 UTC
