### ISSUE TITLE
Not Works with Site Already Logedin

### ISSUE THREAD

**Issue by atulc007** [jarrodek/ChromeRestClient#536] opened 2016-04-19 16:23 UTC
Earlier when This plugin use to work in same tab with chrome then I can access Browsers Cookies so I can use it to access REST API of password protected sites which I have access to Like sharepoint. But now since it run as a separate application and those features work no more.

**Comment by sharepointknight** [comment] 2016-04-20 18:31
I have the same problem as well.

**Comment by jarrodek** [comment] 2016-04-20 21:33
Duplicate of #487

**Closed by jarrodek** 2016-04-20 21:33 UTC
