### ISSUE TITLE
Unable to select existed project on new request saving

### ISSUE THREAD

**Issue by Activuss** [jarrodek/ChromeRestClient#897] opened 2016-11-16 11:31 UTC
Your description here
Existing project names now showed on new request creation
## Expected outcome
What should happen?
If I don't want to create new project I should be able to select existed one from dropdown
## Actual outcome
What happened?
No dropdown with existed projects
## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.71
Platform: Windows (7)

## Steps to reproduce
1. Create new request
2. Click save
3. See pop-up where you can set request name and project name with absent dropdown.
![screenshot_4](https://cloud.githubusercontent.com/assets/5096913/20345682/f6affd4e-ac00-11e6-97d4-adff026c1a74.png)

**Comment by jarrodek** [comment] 2016-11-21 13:25
Hi,

Thank you for issue report. I believe it is a duplicate of #886 so I'm closing this one.

**Closed by jarrodek** 2016-11-21 13:25 UTC

**Comment by jarrodek** [comment] 2016-11-23 15:17
It is merged already with the main branch but now it is tested in test channels. Soon it will be released to public.
