### ISSUE TITLE
Unable to use Advanced Rest Client with endpoints that require form authentication

### ISSUE THREAD

**Issue by michaelschem** [jarrodek/ChromeRestClient#461] opened 2016-04-11 15:31 UTC
In the past when I needed to post to an endpoint behind a form login, I would make the request to the actual endpoint, the server would realize I am unauthenticated and would return a redirect, I would click on this redirect, a new tab would open and I would sign in.  Now, if I click on the link of the redirect location it changes the location of where the request points and does not open another tab.

## Expected outcome
I should be able to authenticate to the from in a separate page that carries the authentication cookie over to Advanced Rest Client.

## Actual outcome
It seems like the cookie is not transferred even if I login to the server on another chrome window.

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. Make request to endpoint that is behind login screen.
2. Open link to login screen in chrome and authenticate.
3. Make request again from step one, it will give you the authentication page again because the cookie has not transferred to arc.

**Comment by jarrodek** [comment] 2016-04-11 15:39
The app do not share the same cookie storage as regular chrome tab. In this app it won't be possible.

However there should be some authentication settings in the app. Either for providing login and password (basic) and cookie data to send with all request sent to corresponding domain. It's core complicated in case of OAuth but it is planned to implement anyway.

Basically the app should store cookie data received from the server and restore it and the append to the headers list when making a request for the corresponding URL. It should be possible to turn off this behaviour to give more control over the request.

**Comment by michaelschem** [comment] 2016-04-11 15:45
Right, I understand the new version does not share cookies with chrome, but the old version did, and that was a nice feature for the reason above.  Is there anyway I can transfer the cookie manually? I realize I can't do it with developer tools since they are not enabled in this standalone app.

**Comment by jarrodek** [comment] 2016-04-11 16:01
You can just use 'cookie' header with the cookie value in the request. The app do not have access to Chrome cookie storage and there is no such API for apps available. So no, you can't transfer cookies.

**Comment by jarrodek** [comment] 2016-04-11 16:05
This is duplicate of #435 so I'm closing this issue.

**Closed by jarrodek** 2016-04-11 16:05 UTC
Labels: enhancement
