### ISSUE TITLE
Execution Time Goes infinite

### ISSUE THREAD

**Issue by vipullakhtariya** [jarrodek/ChromeRestClient#889] opened 2016-11-14 05:52 UTC
When i try to send send request wtih REST client it goes to infinite execution. I have tried with another system it works fine. I also tried to re install this extension from chrome but problem still exists.
please help...

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 8.9.53.279-stable
Chrome: 54.0.2840.71
Platform: Windows (8.1)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-11-14 15:19
Hi,
Thank you for issue report.

It is a duplicate of #887 so I'm closing this one.

**Closed by jarrodek** 2016-11-14 15:19 UTC
