### ISSUE TITLE
Posts with form parameters never come back with response

### ISSUE THREAD

**Issue by mfogg** [jarrodek/ChromeRestClient#434] opened 2016-04-06 22:34 UTC
When submitting form parameters in a post with Content-Type application/x-www-form-urlencoded to any web address with at least one parameter, the request hangs endlessly with the green status moving status bar cycling continually.

## Expected outcome
What should happen?
The request should be sent to the server.

## Actual outcome
What happened?
The request hangs endlessly and no response ever comes back.

## Versions
App: 6.1.10.93-stable
Chrome: 48.0.2564.109
Platform: Linux (-)

## Steps to reproduce
1. Create a request to any url with Content-Type: application/x-www-form-urlencoded
2. Add at least one parameter to the data form to post
3. Click the "send" button.

**Comment by jarrodek** [comment] 2016-04-07 11:06
I can't reproduce the problem now:
![image](https://cloud.githubusercontent.com/assets/3320020/14348255/2c86e20a-fcb3-11e5-98f4-78bef7cc7441.png)

However it is probably connected to the bug where the URLSearchParams caused a problem. This interface was enabled in Chrome 49 which missed my attention. It's fixed in beta now.

Can you please test the beta channel of the app and confirm either issue still exists there or not? Follw the instructions at https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel to install beta.

**Comment by mfogg** [comment] 2016-04-07 22:38
I installed the beta, but now when I try to launch the beta app it opens a blank window.

The developer tools console says:
Failed to load resource: net::ERR_FILE_NOT_FOUND 
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/bower_components/font-roboto/roboto.html

Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/elements/elements.js

Uncaught ReferenceError: CodeMirror is not defined(anonymous function) @ code-mirror-custom.js:10(anonymous function) @ code-mirror-custom.js:12
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/scripts/code-mirror-custom.js

**Comment by jarrodek** [comment] 2016-04-07 23:37
I've fixed it today. There was one script that used `let` keyword outside strict mode. Because of it whole main script had broken. 
First missing import means nothing. I'll deal with it later. But it's just a font.

**Comment by mfogg** [comment] 2016-04-08 00:34
Now the window loads with the Welcome information, however clicking the button for the sidebar causes the sidebar to open completely blank.  Here's what the console output shows:

This file is deprecated. Please use 'iron-flex-layout/iron-flex-layout-classes.html', and one of the specific dom-modules instead
elements.js:7624
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/elements/elements.js

This file is deprecated. Please use 'iron-flex-layout/iron-flex-layout-classes.html', and one of the specific dom-modules instead
elements.js:7625
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/elements/elements.js

Uncaught ReferenceError: URLSearchParams is not defined
elements.js:23876
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/elements/elements.js

Uncaught ReferenceError: CodeMirror is not defined
(anonymous function) @ code-mirror-custom.js:10
(anonymous function) @ code-mirror-custom.js:12
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/scripts/code-mirror-custom.js

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
chrome-extension://epgngalmiadbjnoompchcohonhidjanm/elements/elements.js

**Comment by jarrodek** [comment] 2016-04-08 02:24
I've fixed it few hours ago. URLSearchParams was enabled in Chrome 49 and I wasn't aware of it. Minimum upgrade version was 47. Now I fixed it in beta (6.14.15.113) and there should be no error.

**Comment by mfogg** [comment] 2016-04-08 17:32
I can confirm the sidebar now works correctly in the beta app.  I've tested the original reported issue on the beta app and I can no longer reproduce it.  Looks like it's fixed. Thanks!

**Closed** 2016-04-08 18:22 UTC
