### ISSUE TITLE
Send button is hidden behind 'Explore' option

### ISSUE THREAD

**Issue by sandelirious7** [jarrodek/ChromeRestClient#868] opened 2016-11-08 18:44 UTC
If the request body is large, 'Send' button is hidden behind the 'Explore' option, hence unable to click it.
 
![sendbutton is hidden](https://cloud.githubusercontent.com/assets/22677884/20112213/791b268c-a611-11e6-87e3-43bc19df744d.jpg)

**Comment by jarrodek** [comment] 2016-11-08 19:02
It's a duplicate of the #837.
And it's also fixed already. I'm rolling out update at the moment.

**Closed by jarrodek** 2016-11-08 19:02 UTC
