### ISSUE TITLE
Response Copy To Clipboard Not Working

### ISSUE THREAD

**Issue by ebinms** [jarrodek/ChromeRestClient#1067] opened 2017-10-16 07:00 UTC
Copy to clipboard option is not working.

![capture](https://user-images.githubusercontent.com/28801400/31598906-cd681a2e-b26d-11e7-92e7-8a2fda20b3d5.PNG)

**Comment by jarrodek** [comment] 2017-10-16 15:54
Hi,
Thank you for the issue report. This is duplicate of #1070 .
Also I just fixed it. I'll release the update in an hour or so.

**Closed by jarrodek** 2017-10-16 15:54 UTC
