### ISSUE TITLE
History Tab Is messed up

### ISSUE THREAD

**Issue by faizalsheriff** [jarrodek/ChromeRestClient#888] opened 2016-11-13 01:52 UTC
Your description here
History tab is messed up in the new version
## Expected outcome
What should happen?
Last used API should show up on the top
## Actual outcome
What happened?
The API order is messed up
## Versions
App: 8.9.53.279-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-11-14 15:26
Hi,
Thank you for the issue report.
This is a duplicate of #883 so I'm closing this one.

**Closed by jarrodek** 2016-11-14 15:26 UTC
