### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT when no direct internet connection

### ISSUE THREAD

**Issue by dao-s33k3r** [jarrodek/ChromeRestClient#534] opened 2016-04-19 14:43 UTC
Hello,

when trying to use the ARC without a direct internet connection ( I'm currently using a proxy ) I get the following error when trying to post to an URL (that works when accessed directly from the browser):

> There was an error during the request
> 
> net::ERR_CONNECTION_TIMED_OUT

The older version worked perfectly but since updated recently It stopped working.

## Expected outcome
Should get a reply from the server.

## Actual outcome
I get the mentioned error.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Windows (8.1)

## Steps to reproduce
1. No direct internet connection
2. Proxy in browser
3. Try posting to any URL

**Comment by jarrodek** [comment] 2016-04-19 15:06
Hi,

Thanks for issue report. It is a duplicate of #432. Generally it won't be fixed for the reason described in this thread (especially my last comment). 
You can always create issue report in Chromium project but my discussion with Chromium team member was really convincing and I don't see possibility to change this behaviour in the future.

Thanks.

**Closed by jarrodek** 2016-04-19 15:06 UTC
