### ISSUE TITLE
Cookies not being stored on packaged version of app, causing 401 headers?

### ISSUE THREAD

**Issue by lferreira457** [jarrodek/ChromeRestClient#546] opened 2016-04-20 01:28 UTC
The packaged version of the app doesn't seem to be storing cookies unlike the browser version. If i try to create a new session via one of my login endpoints, I now get 401 codes for other endpoints which require authentication.

![screen shot 2016-04-20 at 11 24 49 am](https://cloud.githubusercontent.com/assets/8458271/14660713/fc327ad2-06ea-11e6-90fb-315129490ebe.png)

**Comment by jarrodek** [comment] 2016-04-20 11:35
Duplicate of #487

**Closed by jarrodek** 2016-04-20 11:35 UTC
