### ISSUE TITLE
Please provide a setting to override the default connection timeout

### ISSUE THREAD

**Issue by schubertf** [jarrodek/ChromeRestClient#562] opened 2016-04-20 14:13 UTC
I am using the REST client to test a REST service that takes a while to process the request.
Unfortunately, the REST client times out when I call my service.
Please provide a setting that can be used to override the default connection timeout.

Thanks for your help.
Regards

**Comment by jarrodek** [comment] 2016-04-20 14:52
Duplicate of #502

**Closed by jarrodek** 2016-04-20 14:52 UTC
