### ISSUE TITLE
Missing authorization header

### ISSUE THREAD

**Issue by reuvenk** [jarrodek/ChromeRestClient#453] opened 2016-04-10 14:31 UTC
When using authorization with a GET request, the server did not get the authorization header used

## Expected outcome
What should happen?
authorization should be sent

## Actual outcome
What happened?
the server did not get the authorization header used

## Versions
App: 6.19.17.118-stable
Chrome: 48.0.2564.116
Platform: Windows (7)

## Steps to reproduce
1. Send Get Request with authorization
2. check server request on server

**Comment by jarrodek** [comment] 2016-04-11 09:25
Can't reproduce the problem.
Is there anything specific with this header? Are other headers received by server? 
There is nothing special about this header in the app and it is sent as other header. 

Is the problem persists in both "raw" and "form" editor?

**Comment by daannet** [comment] 2016-04-11 14:04
I have the same issue, 

When i open the request in the history the Bearer Authorization header has been changed to Basic and the key is base64 encoded.

**Comment by jarrodek** [comment] 2016-04-11 15:15
Can you see this header in the response panel in "Request headers" tab?

![image](https://cloud.githubusercontent.com/assets/3320020/14432054/5d515f32-0000-11e6-8c2f-81c231ae687c.png)

This headers are constructed in the transport library and contains final set of headers sent to the remote machine.

**Comment by reuvenk** [comment] 2016-04-12 12:11
I am sorry,

I can't check it on again, but what I can tell you it happened after the
last upgrade, on my machine on on other developers machines.
The problem did not happened when using a different rest client tool (DHC
Rest Client).

Reuven.

**Comment by jarrodek** [comment] 2016-04-12 13:31
OK, but it may be manny issues here and I'm not sure to which you are referring to. Since I can see authorization header on server side when I'm sending them with the app the issue seems invalid. So can you please give me some details about the issue. 
How do you know the header is missing on server side? Or maybe it is related to the issue #452 where invalid server configuration or issue with code causing an error.

**Comment by myousuffazal** [comment] 2016-04-15 06:23
I will second this, the Authorization Header is not being passed despite it being displayed in the Request headers tab. It was working properly with the previous version of the app when it was an extension. Since I've upgraded to the app, the Authorization Header has stopped working.

Just to clarify: It can not be coding or a server error, because:
1. It was working with the previous version.
2. It is working with all the other ways I've tried, through php code, through Postman app, etc.

**Comment by jarrodek** [comment] 2016-04-15 09:10
Is it possible that the server recognizes letter case? I've run test and I can't reproduce the issue.

**Comment by myousuffazal** [comment] 2016-04-15 09:32
Even if such was an issue, the same headers should not be working with other apps. Though what might help is that I've noticed that everywhere Authorization Header is passed with a capital A, so incase your app is converting it into smaller case, that might be causing the issue.

**Comment by jarrodek** [comment] 2016-04-15 10:08
If that is the case I would close the issue as WAI. According to the spec headers are case insensitive. The app is using javascript build-in Headers object that transforms headers to lowercase when getting back values from it. So if server code do not recognize header it's an issue with server code and not with the app.

**Comment by jarrodek** [comment] 2016-05-09 18:57
I'm closing it because of lack of activity.

**Closed by jarrodek** 2016-05-09 18:57 UTC
Labels: awaiting-response, WAI
