### ISSUE TITLE
ERR_SSL_CLIENT_AUTH_CERT_NEEDED

### ISSUE THREAD

**Issue by kimivitebsk** [jarrodek/ChromeRestClient#648] opened 2016-05-03 14:40 UTC
Hello!

I make request to https:########################
and get error
ERR_SSL_CLIENT_AUTH_CERT_NEEDED

In VisualStudio2015 i make this request and get good responce.
Thanks

## Versions
App: 7.12.30.183-stable
Chrome: 50.0.2661.94
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by Izuzusama** [comment] 2016-05-04 01:17
I believe is Duplicate of #621

**Comment by jarrodek** [comment] 2016-05-16 21:18
This is fixed by https://github.com/jarrodek/ChromeRestClient/commit/89973b258fe80f0bcc33814111917d6ef272617c

**Closed by jarrodek** 2016-05-16 21:18 UTC
