### ISSUE TITLE
New ChromeRestClient can't use existing http seesion

### ISSUE THREAD

**Issue by Justin01Wu** [jarrodek/ChromeRestClient#576] opened 2016-04-20 21:09 UTC
In the previous version, it can use the http session to send request if user already login in another tab

## Expected outcome
it should use existing http session to send request.

## Actual outcome
Now it popup a window, and can't use http seesion to send request, 

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-04-20 21:33
Duplicate of #487

**Closed by jarrodek** 2016-04-20 21:33 UTC
