### ISSUE TITLE
We've stopped using your product due to your lack of cookie support.

### ISSUE THREAD

**Issue by trailerldn** [jarrodek/ChromeRestClient#528] opened 2016-04-19 13:37 UTC
What do we do if users need to be authenticated via cookies?!
Your new version no longer supports this and as such we've moved to Postman.

## Expected outcome
Re-enable support for authentication through cookies.

## Actual outcome
Your new version no longer supports this and as such we've moved to Postman.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (8.1)

## Steps to reproduce
1. Authenticate into a website that saves state in a cookie.
2. Access an API which relies on your cookie state.
3. Failure.

**Comment by jarrodek** [comment] 2016-04-19 14:47
Duplicate of #487

**Closed by jarrodek** 2016-04-19 14:47 UTC
