### ISSUE TITLE
Windows NTLM pass-through authentication isn't working after update

### ISSUE THREAD

**Issue by infl3x** [jarrodek/ChromeRestClient#508] opened 2016-04-19 00:05 UTC
Windows NTLM pass-through authentication isn't working after update. Always comes up with '401 - unauthorised'. The same request works fine in Postman (another Chrome extension).

## Expected outcome
The app should either pass-through my Windows authentication credentials or it should ask for them after the NTLM challenge response is received.

## Actual outcome
The app doesn't send my Windows authentication credentials and so receives a 401 response.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (10)

## Steps to reproduce
1. Access an endpoint with Windows Authentication configured and enabled.
2. Receive 401 error

**Comment by jarrodek** [comment] 2016-04-19 01:09
NTLM is not currently supported in the app. However it looks like there is a gap in the app's functionality that should be filled.

**For my reference: **
XHR implementation: 
https://github.com/erlandranvinge/ntlm.js/blob/master/ntlm.js
However when using sockets remember that the whole handshake process must be done on the same socket (http://www.cisco.com/c/en/us/support/docs/security/web-security-appliance/117931-technote-ntml.html). Therefore it must be included in socket-fetch library - not only the app.
This might be opportunity to implement interfaces to support NTLP and Digest authentication in the library and finally OAuth2. Each interface would be called when the authentication is required (depending on 401 status message) without closing a socket (as it is right now). Then accepting credential from the user/database it may use the same configuration to re-run the request without creating new request + socket objects.

**Comment by jarrodek** [comment] 2016-04-19 01:20
And it is actually duplicate of the #472

**Closed** 2016-05-09 18:49 UTC
Labels: bug
