### ISSUE TITLE
Headers sent are not keeping capitalisation

### ISSUE THREAD

**Issue by conorot** [jarrodek/ChromeRestClient#573] opened 2016-04-20 18:36 UTC
When sending a GET,PUT,POST, etc request with a custom header, the system will apply a lower case conversion to the header key. e.g. sending an "Authorisation" header, will actually send an "authorisation" header - not readable by the target system. 

## Expected outcome
The header should be set exactly as the user inputs it regardless of case

## Actual outcome
Header "Authorsation" capitalisation is removed so that this is sent as "authorisation" - causing a system failure on the receiving API

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (10)

## Steps to reproduce
1. Set any header with a capitalised letter
2. ARC makes the header all lower case

**Comment by jarrodek** [comment] 2016-04-20 21:01
Hi,
Thank you for an issue report.

Closing as duplicate of #491 #453 and #472

**Closed by jarrodek** 2016-04-20 21:01 UTC
