### ISSUE TITLE
History - Need to scroll to the top for request details when double clicked from the bottom

### ISSUE THREAD

**Issue by abdullacm** [jarrodek/ChromeRestClient#550] opened 2016-04-20 06:29 UTC
In the history listing, when more records are in the history and we are in the bottom, double click any record and we have to scroll to the top to see the request details

## Expected outcome
The request details to be shown in right to the clicked record instead scrolling to top

## Actual outcome
User have to scroll to top to see the request details (its very difficult, may be the user want to click  on the next record, he has to scroll to bottom and top for the request details)

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (8.1)

## Steps to reproduce
1. Go to history (hope 100+ records in the history)
2. Scroll to the bottom, and double click on any record from the bottom area
3. have to scroll to the top to see the request details

**Comment by jarrodek** [comment] 2016-04-20 11:59
Duplicate of #513

**Closed by jarrodek** 2016-04-20 11:59 UTC
