### ISSUE TITLE
Can't paste into request URL with keyboard shortcut

### ISSUE THREAD

**Issue by bsiepert** [jarrodek/ChromeRestClient#917] opened 2016-12-02 22:03 UTC
Your description here
I attempted to paste a URL into the corresponding field under the request pane using command-v 
## Expected outcome
I would expect that it would paste the value from the clipboard 
## Actual outcome
The value was not pasted. Using the mouse context menu to paste worked just fine.
The same problem exists for all fields as far as I can tell.
## Versions
App: 8.19.60.296-stable
Chrome: 54.0.2840.98
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2017-01-17 18:54
Hi,

I can't reproduce the problem.
Are you sure that you are focused on the field? 

I'm closing this as WAI but feel free to reopen if needed.

**Closed by jarrodek** 2017-01-17 18:54 UTC
