### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Bharath014** [jarrodek/ChromeRestClient#523] opened 2016-04-19 12:02 UTC
Hi Team

Am getting 401 unauthorized . Please help with the issue and telll me where to give the credentials. 

Thanks & Regards,
Bharath Govidnaraju

**Comment by puffluna** [comment] 2016-04-19 12:39
I am getting the same.  I was fine until I took the upgrade yesterday.

**Comment by jarrodek** [comment] 2016-04-19 14:42
@Bharath014 is this a duplicate of the #517?

**Comment by Bharath014** [comment] 2016-04-19 14:56
Yes this is the same as 517

**Closed** 2016-04-19 15:07 UTC
Labels: awaiting-response
