### ISSUE TITLE
Timout configuration is not available.

### ISSUE THREAD

**Issue by vaalu** [jarrodek/ChromeRestClient#618] opened 2016-04-25 21:20 UTC
Your description here
Timout configuration is not available.

## Expected outcome
What should happen?
For requests with lengthy duration, timeout occurs.

## Actual outcome
What happened?
For requests with lengthy duration, timeout occurs.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. Try accessing a delayed restful service 
2. Timeout occurs on the same
3.

**Comment by jarrodek** [comment] 2016-04-25 22:57
Hi,

Thank you for issue report.
It is duplicate of #613 #605 and #601 

As per this I'm closing it as a duplicate.

**Closed by jarrodek** 2016-04-25 22:57 UTC
