### ISSUE TITLE
Name column in Saved view is not able to be fully presented if it's too long.

### ISSUE THREAD

**Issue by archerwq** [jarrodek/ChromeRestClient#516] opened 2016-04-19 08:59 UTC
Your description here
See title.

## Expected outcome
What should happen?
See title.

## Actual outcome
What happened?
See title.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.110
Platform: Mac OS X (10_11_1)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-04-19 10:58
Duplicate of #468

**Closed by jarrodek** 2016-04-19 10:58 UTC
