### ISSUE TITLE
Response Payload Disappeared

### ISSUE THREAD

**Issue by artifex223** [jarrodek/ChromeRestClient#933] opened 2017-01-05 21:22 UTC
This was working fine earlier today, but now I cannot see the response payload.

## Expected outcome
I should be able to view the response

## Actual outcome
I can only see response headers, request headers, redirects, and timings

## Versions
App: 8.19.60.296-stable
Chrome: 55.0.2883.95
Platform: Mac OS X (10_12_1)

## Steps to reproduce
1. Send a request
2. View response

**Comment by jarrodek** [comment] 2017-01-06 17:45
Hi,

Thank you for issue report. 
The app hasn't changed for weeks now so it can't be caused by the app if it worked earlier. Are you sure that there's a response from the server?

**Comment by jarrodek** [comment] 2017-01-17 18:55
I'm closing this for now. Reopen if needed.

**Closed by jarrodek** 2017-01-17 18:55 UTC
Labels: awaiting-response
