### ISSUE TITLE
Sending files and POST data doesn't work anymore

### ISSUE THREAD

**Issue by upanisad** [jarrodek/ChromeRestClient#972] opened 2017-03-06 15:14 UTC
Sending files and POST data doesn't work anymore

## Expected outcome
I use ARC to test an app backend I'm working on. I need to be able to send a series of text fields plus a file. It has Always worked flawlesly for years. Now, I've just re-opened ARC, sporting a nice new look, but file sending doesn't work anymore!
I use a POST request, type the fields in "Data form" section as I've always done, then add a file in "Files" section. It displays a message that says "The Content-Type header will be finally changed to "multipart/form.data" during the request". 
Apache/PHP server used to fill correctly $_POST and $_FILES global variables.

## Actual outcome
When I send the form, the Apache/PHP server gets empty arrays $_FILES and $_POST. If I delete the file in ARC, $_POST is ok, but I need the file too! I tried to switch manually the POST type in ARC, with no results.

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (10)

## Steps to reproduce
1. Choose POST and type some data in "Data form" and add a file in "File"
2. Send
3. Debug on Apache/PHP server

**Comment by jarrodek** [comment] 2017-03-06 15:16
Hi,

Thank you for issue report. It is confirmed bug in Chrome. I'm currently working on solution for that issue before new Chrome release.

Closing as a duplicate of #945.

**Closed by jarrodek** 2017-03-06 15:16 UTC
