### ISSUE TITLE
Saved list Name is too short

### ISSUE THREAD

**Issue by koolook** [jarrodek/ChromeRestClient#525] opened 2016-04-19 12:42 UTC
Please increase the width of Name column in saved list. 16 characters can not display anything meaningful. There are oversized Method and wide URL (which is less important then Name) columns that could be tightened.
Existing tooltip functionality just does not work. It never shows the whole name.  Sliding info panel on the right is too time consuming when you browse the list.

**Comment by jarrodek** [comment] 2016-04-19 14:44
Duplicate of #468

**Closed by jarrodek** 2016-04-19 14:44 UTC
