### ISSUE TITLE
Adding Authorization header, no pencil appears

### ISSUE THREAD

**Issue by ejimsmith** [jarrodek/ChromeRestClient#686] opened 2016-05-31 17:52 UTC
I try adding an Authorization header, and when I do the pencil that allows me to enter the credentials doesn't appear.  The line only contains a text box to enter the Header value, and an X to remove the header.  I can't seem to figure out how to bring up the pencil so I can enter the credentials I want to pass.

**Comment by ejimsmith** [comment] 2016-05-31 17:54
I found a workaround, if you add the Authorization header, and then click "Raw headers" or "Header sets", and then click back to "Headers form", the pencil will appear.  I still think this is an issue that should be addressed though.

**Comment by jarrodek** [comment] 2016-06-01 17:06
Hi,
Thanks for the issue report. I can't reproduce the problem though. It always adds (at least me) the pencil when I either type whole header name by my own or I'll use a suggestion. It do the same for lower and upper case. 
Is there an error in a log viewer regarding this issue? You can find it in dropdown menu in  left panel.

**Comment by ejimsmith** [comment] 2016-06-01 17:14
I think I figured out the difference.  When i make a new request that
pencil appears, when I start with a request from the History section, one
that already has headers, it won't appear.  This doesn't cause an error in
the log.

I have a couple workarounds though, so I'm not longer concerned. I
appreciate your response!

All the best!
Jim Smith

**Comment by jarrodek** [comment] 2016-06-01 17:30
OK, thanks for clarifying.
However still I can't reproduce it. What is the version of the app you are using?

**Comment by jarrodek** [comment] 2016-07-25 16:29
This issue has been fixed already and the fix is in stable channel.

**Closed by jarrodek** 2016-07-25 16:29 UTC
Labels: awaiting-response
