### ISSUE TITLE
Host in missing when loading saved project

### ISSUE THREAD

**Issue by undyingshadow** [jarrodek/ChromeRestClient#625] opened 2016-04-26 17:50 UTC
Whenever I load my saved project, the URL is now missing. See screenshot:

![screen shot 2016-04-26 at 12 45 25 pm](https://cloud.githubusercontent.com/assets/18685491/14828623/706c1de2-0bad-11e6-8469-fd067b6ead7a.jpg)

**Comment by dehemke** [comment] 2016-04-26 19:27
+1 also happens when loading from history.

Host, path, query parameters are not loaded in the UI - although the call does seem to be executing properly.

**Comment by jarrodek** [comment] 2016-04-27 14:41
Hi,

Thank you for issue report. I think it was fixed in yesterday's release. However, try to close the URL panel (to simple view) and check if this is working. And probably your app has been updated already so the issue is fixed. Just let me know.

**Comment by dehemke** [comment] 2016-04-27 14:58
Confirmed fixed.

**Comment by jarrodek** [comment] 2016-04-27 18:21
Thank you!

**Closed by jarrodek** 2016-04-27 18:21 UTC
Labels: awaiting-response
