### ISSUE TITLE
Request URL fields are completely broken, app is unusable

### ISSUE THREAD

**Issue by gdavidmac** [jarrodek/ChromeRestClient#1089] opened 2017-10-18 16:32 UTC
The Request URL fields are completely broken in multiple ways.

1. A clean installation of the app gives error Failed to construct 'URL': Invalid URL.

2. The Request URL field should show the same URL contents when in collapsed mode (single field) and expanded (host/path/query parameters as separate fields) mode. Currently, changes to the field in collapsed mode do not change the URL to which the request is sent if data exists in the fields in expanded mode.

3. Additionally, deleting data from the fields in expanded mode does not work - the client will continue to send the request using the old field values.

These issues have made the app completely unusable.

# Steps to reproduce
1. Do a clean install of the app (uninstall first if necessary).
2. Enter a URL, and send the request.

The request should be sent to the proper URL.

3. Enter a request URL into the host/path fields in expanded mode and add a query parameter. Send the request.
5. Now change the host/path/query parameter fields (new host, new path, delete the query parameter) and send the request again and observe.

The second request should be properly sent to the second URL entered.

6. Enter a request URL into the host/path fields in expanded mode and add a query parameter.
7. Collapse the fields and edit the Request URL field.
8. Expand the fields again and observe.

Entering a new value into the Request URL field in collapsed mode should change the values in the host/path/parameters fields in expanded mode.

## Expected outcome

1. Entering a value into the Request URL field in collapsed or expanded mode should work properly and send the request to the proper entered URL.

2. Editing the Request URL field in collapsed mode should properly change the values when the fields are expanded, and vice versa.

3. Values deleted from fields in expanded mode should not continue to be sent in the request

## Actual outcome
1. Sending a request to a URL with a clean installation errors out with "Failed to construct 'URL': Invalid URL"

2. The request will be sent to the old URL again, without picking up any changes.

3. The value shown in the collapsed Request URL field is unrelated to the values in the expanded host/path/parameters fields. Changing the collapsed field value has no effect on the expanded fields' values, and vice versa.

![image](https://user-images.githubusercontent.com/18412969/31730171-1df2b3b8-b3ff-11e7-92c7-5a1ef57573cb.png)

# Versions
App: 10.0.5
Chrome: Version 55.0.2883.87 m

**Comment by gdavidmac** [comment] 2017-10-18 16:38
Do these upgrades undergo some kind of sanity testing before release? This issue completely breaks the app's functionality, and it seems difficult to believe this could have been missed if any sanity testing of releases is occurring.

**Comment by jarrodek** [comment] 2017-10-19 00:37
Hi,

Thank you for the issue report.
I can't reproduce the problem. This is steps reproduction. Version 10.0.5.

## step 1
![image](https://user-images.githubusercontent.com/3320020/31748651-7597f5c2-b429-11e7-9cb3-9ea527c76722.png)

## Step 2

![image](https://user-images.githubusercontent.com/3320020/31748666-8e0ffbc2-b429-11e7-8a23-f4d2bf27d8c1.png)

Notice change in the source message in next steps that confirms that URL has been changed

## Step 3

![image](https://user-images.githubusercontent.com/3320020/31748701-c3bbd37c-b429-11e7-94b7-04d885404c08.png)

## Step 4

![image](https://user-images.githubusercontent.com/3320020/31748717-e611286e-b429-11e7-8115-55e1f0b8102e.png)


## Step 5

![image](https://user-images.githubusercontent.com/3320020/31748734-0c5976ca-b42a-11e7-9edc-114089fb5722.png)

## Step 6

![image](https://user-images.githubusercontent.com/3320020/31748749-2ba614de-b42a-11e7-80a7-e587cdb0e041.png)

## Step 7

![image](https://user-images.githubusercontent.com/3320020/31748759-3eabd064-b42a-11e7-901e-bf52b143aa5b.png)

## Step 8

![image](https://user-images.githubusercontent.com/3320020/31748779-65e6033e-b42a-11e7-8ef5-43b400cb49f5.png)

and then 

![image](https://user-images.githubusercontent.com/3320020/31748783-6d60acea-b42a-11e7-8c74-d648be136e9a.png)

and then execution:

![image](https://user-images.githubusercontent.com/3320020/31748801-8dfca440-b42a-11e7-85c8-39048f6c4d93.png)



As for the tests you can find it here: 
https://github.com/advanced-rest-client/url-input-editor/tree/stage/test
Test execution: https://travis-ci.org/advanced-rest-client/url-input-editor/builds/281725997

I've noticed though that you are using outdated Chrome. It's 6 versions behind current version. It may cause a problem. I'm not testing the app for that old browsers.

I'm closing the issue as WAI.

**Closed by jarrodek** 2017-10-19 00:37 UTC

**Comment by gdavidmac** [comment] 2017-10-19 01:58
"I've noticed though that you are using outdated Chrome. It's 6 versions behind current version. It may cause a problem. I'm not testing the app for that old browsers."

@jarrodek "that old browsers"? Chrome 55.02883 was released in December 2016, just under 11 months ago. I'm not sure on what planet 11 months is "that old". Any enterprise with strict security requirements and slower upgrade paths will commonly require versions of software that are *at least* that old - if you've ever worked in such an environment, you would be well aware that software versions that are *years* out of date are common.

If you are going to refuse to even consider testing your application against browser versions that are a few months old you should be very clear about the fact that your app is not guaranteed to work on anything other than the latest browser version, and that you will refuse to support any older versions. Your refusal to test or support any browser versions other than the latest version means your application is unusable in any of those environments. At the very least, you should be open up front about the severe restrictions on your willingness to test your application, and its resultant instability for many users.

**Comment by jarrodek** [comment] 2017-10-19 08:04
@gdavidmac 
I am putting a lot of effort to maintain the application, develop new features and make sure everything is working. I said that the browser is updated but that is not a reason of the behavior anyway. This element passes tests even on IE11 which is quite problematic browser.
My ability to fix all issues are limited to my free time and I'm really trying here.
The project is completely free and open. If you can help and contribute, please do so. Clone https://github.com/advanced-rest-client/url-input-editor and test it in your environment. If you notice any problem please let me know. 

I've just added more detailed tests to the element and configuration for sauce labs to tests Chrome 55. Here's result: https://saucelabs.com/beta/tests/9927d920bc3548318929c6cd24c5f075/commands#2
I know it's frustrating that something's not working. But by any measure  it is working anywhere where I tried to test. It is possible that in your "enterprise environment" there are some limitations added to Chrome. I am not able to check every possible scenario. That is why I'm usually asking people for more detailed description. Even though your was quite precise I still can reproduce the problem. If I could I'd take an action.
