### ISSUE TITLE
Switching between saved requests keeps old data form.

### ISSUE THREAD

**Issue by ardanika** [jarrodek/ChromeRestClient#638] opened 2016-04-27 12:46 UTC
I open saved request A that has form data, Update some values, save it (overwrite), and send that request. Next I open request B, and instead of form data for request B I get form data from request A.

If I close ARC and reopen it and load request B, I get the correct form data. 

## Versions
App: 7.9.29.179-stable
Chrome: 48.0.2564.97
Platform: Windows (7)

**Comment by jarrodek** [comment] 2016-04-27 13:50
Hi,

Thank you for issue report.
I can't reproduce the problem. Is your directions accurate? Is it possible for you to send me request data for both requests? I'd like to imitate the same conditions on my environment and test it again.

Maybe you can see any error message in log viewer? (left nav > bottom buttons > More)

**Comment by ardanika** [comment] 2016-04-27 14:24
I have a video of the problem but I don't want to post it here. Is there an email address I can send it to?

**Comment by jarrodek** [comment] 2016-04-27 14:27
Sure,

You can send it to jarrodek@gmail.com.
I'll test it when I have a chance to do it.

**Comment by jarrodek** [comment] 2016-05-04 23:58
Thanks for the movie and the issue report. It was fixed in latest release.

**Closed by jarrodek** 2016-05-04 23:58 UTC
Labels: test-needed
