### ISSUE TITLE
ARC does not take into account the encoding of the document

### ISSUE THREAD

**Issue by gbatanov** [jarrodek/ChromeRestClient#1069] opened 2017-10-16 10:29 UTC
content-type:
text/html; charset=UTF-8

## Expected outcome
correct russian text

## Actual outcome
Ð¡Ð¾ÑÐ¾Ð²ÑÐµ ÑÐµÐ»ÐµÑÐ¾Ð½Ñ Ð±ÐµÐ· Ð¿Ð¾Ð´ÐºÐ»ÑÑÐµÐ½Ð¸Ñ ÐÐºÑÐµÑÑÑÐ°ÑÑ ÐÐ°Ñ
![image](https://user-images.githubusercontent.com/2103439/31607676-f08613f0-b275-11e7-891e-34bdc92d6078.png)

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2017-10-16 15:56
Than you for the issue report.
I'm marking this as a duplicate of #1065 since i've started conversation there.`

**Closed by jarrodek** 2017-10-16 15:56 UTC
