### ISSUE TITLE
Url 

### ISSUE THREAD

**Issue by htaneja** [jarrodek/ChromeRestClient#630] opened 2016-04-26 19:03 UTC
I would like to see the complete url from my history, in order to pick up the one i like very quickly. 
Also the table columns under history are not adjustable - I tried to get the complete url by few tricks nothing works for now.
## Expected outcome

What should happen?
I should be able to quickly jump to the request from history by glancing at url
## Actual outcome

What happened?
I am not able to see the complete url unless i open the request from history.
## Versions

App: 7.9.29.179-stable
Chrome: 50.0.2661.87
Platform: Windows (7)
## Steps to reproduce
1. Go to history and try to locate the complete url.
2. 
3.

**Comment by Izuzusama** [comment] 2016-04-27 08:25
You can double click the row and on the right side it will show you the whole url

**Comment by jarrodek** [comment] 2016-04-27 14:10
Hi,

You can either maximize the window or double-click on the item to see details.
It may be usable to have adjustable columns but 1) it's not easy to deliver and 2) require time to code. 
I accept this issue (as a duplicate of #468). 

PR are welcome here :)

Thanks

**Comment by gitdode** [comment] 2016-05-23 16:53
Maybe the URL could break into multiple lines? Like that all information would be visible in the history without having to adjust column widths or double click.
This is the only "issue" I have with this otherwise nice, user-friendly and very helpful tool.
Thanks for it by the way!

**Comment by jarrodek** [comment] 2017-10-04 01:31
The list has been now redesigned to show as much URL as possible,

**Closed by jarrodek** 2017-10-04 01:31 UTC
Labels: enhancement, Usability
