### ISSUE TITLE
multipart/form-data requests don't work with other form parameters

### ISSUE THREAD

**Issue by oryanm** [jarrodek/ChromeRestClient#971] opened 2017-03-02 20:39 UTC
info message says the header will be changed to "multipart/form-data" during the request but it does not.

## Expected outcome
Content type should be 'multipart/form-data'

## Actual outcome
Content type remains 'application/x-www-form-urlencoded'

![image](https://cloud.githubusercontent.com/assets/1687920/23525832/d0a54a36-ff5d-11e6-8c04-d740f63ce676.png)

## Versions
App: 9.14.64.305-stable
Chrome: 56.0.2924.87
Platform: Windows (7)

## Steps to reproduce
1. send PUT request with a file and another parameter to server that expects Content type`multipart/form-data`.

**Comment by jarrodek** [comment] 2017-03-02 22:43
Hi,

Thank you for the issue report.
Sorry about this issue. It's a bug with Chrome and I already reported it. Chromium team confirmed the bug and they are working on a fix. From my side I'm working on different implementation. But because it's the core module of the application that has many implications it just takes time.

I'm closing this issue as a duplicate of #945. Follow this issue to be notified about the progress.

Thanks.

**Closed by jarrodek** 2017-03-02 22:43 UTC
