### ISSUE TITLE
[enhancement] sort the list of project endpoints phonetically

### ISSUE THREAD

**Issue by justinhelmer** [jarrodek/ChromeRestClient#357] opened 2016-01-13 19:51 UTC
As a project grows, the list of `APIs` tends to grow along with it. Having project-level endpoints is a tremendously useful feature.

That being said, the list grows long enough such that it can be difficult to find what you are looking for. It appears they are currently sorted based on timestamp, or some sort of natural sort order.

It would be very useful if the list were sorted alphabetically; this would make it much easier to pinpoint the request with ease. It seems this could potentially be a simple change with a lot of added benefits.

I think you will find many others will benefit from this as well.

**Comment by justinhelmer** [comment] 2016-01-13 19:53
**Not** a duplicate of [#358](https://github.com/jarrodek/ChromeRestClient/issues/358)

**Comment by jarrodek** [comment] 2016-01-13 23:49
It's a duplicate of #340  :)
It's on my roadmap. I can't do it right now but it will be don in a matter of weeks.

**Closed by jarrodek** 2016-01-13 23:49 UTC
