### ISSUE TITLE
Raw response (plain text) '\n' is ignored - no newline occurs

### ISSUE THREAD

**Issue by RanGold** [jarrodek/ChromeRestClient#529] opened 2016-04-19 13:37 UTC
Raw response (plain text) '\n' is ignored - no newline occurs

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)

**Comment by jarrodek** [comment] 2016-04-19 14:48
Is this a duplicate of #527?

**Comment by RanGold** [comment] 2016-04-19 14:53
Not really. New line occurs when wrapping should occur and not when '\n' is present

**Closed** 2016-08-22 18:56 UTC
Labels: bug, Component: Response panel
