### ISSUE TITLE
POST not sending request body

### ISSUE THREAD

**Issue by suau** [jarrodek/ChromeRestClient#699] opened 2016-06-09 04:38 UTC
I'm locally testing my nodejs server and somehow the POST body with application/json
does not seem to get send properly using curl like below works fine
`curl -H "Content-Type: application/json" -X POST -d '{"id":"myjsonobject"}' http://url.com`

## Expected outcome
POST body should be included

## Actual outcome
POST body is missing

## Versions
App: 7.20.37.203-stable
Chrome: 50.0.2661.102
Platform: Mac OS X (10_11_5)

**Comment by jarrodek** [comment] 2016-06-09 14:02
Hi,

Thank you for issue report.
I can't reproduce the problem. Can you post a source message that you can read in the response panel under request header? It should be something like this:

```
POST / HTTP/1.1
HOST: httpbin.org
content-type: application/json
content-length: 21
 
{"id":"myjsonobject"}
```

**Comment by suau** [comment] 2016-06-09 15:02
Ok this is weird, today I picked the exact same request from the history and started the server exactly as I left it off yesterday and it is working fine. I'll report back if it happens again or I figure out how to reproduce the issue. I would say my server was at fault, but then again it was working properly with curl.

**Comment by jarrodek** [comment] 2016-06-10 12:02
I'm not sure what could have happened here either. If it is working right now it means that it should have been working yesterday - it's the same set of data.
I have nothing to investigate so I'll close this issue. However, if you'll be able to reproduce the problem, please, re-open the issue.

**Closed by jarrodek** 2016-06-10 12:02 UTC
Labels: awaiting-response
