### ISSUE TITLE
Encode and Decode buttons for payload with different content types

### ISSUE THREAD

**Issue by aantoniadis** [jarrodek/ChromeRestClient#363] opened 2016-01-15 09:39 UTC
I have the following body:
`{"a":[1]}`

When I encode it I get:
`%7B%22a%22=%5B1%5D%7D`

When I decode it again I get:
`{"a"=[1]}`

which is not the same as the initial and also it is not a valid json.

I believe that it should be `a == decode(encode(a))`, right?

**Comment by jarrodek** [comment] 2016-01-15 17:00
Endcode / Decode options are only for application/x-www-form-urlencoded encoded data and naturally shouldn't be used on JSON string.
In the future the set of buttons and options available for the payload will depend on recognized content type of the request (based on headers list) so the encode / decode buttons will be visible only when you set proper Content-Type header.  Anyway, it's not an issue with the app so I'm closing this.

**Comment by aantoniadis** [comment] 2016-01-19 22:03
@jarrodek I agree that this is not an issue since it should be used along application/x-www-form-urlencoded  content but wouldn't it be better if it was disabled when the content is not the supported?

**Comment by jarrodek** [comment] 2016-01-20 00:01
That's right but like I said, I'm planning this in future. Actually the issue should stay opened until it will be resolved. However it's not a bug.

**Comment by jarrodek** [comment] 2016-02-28 20:49
In upcoming version (5.0.0) it was redesigned and the only possibility to have this buttons is to set content-type header to application/x-www-form-urlencoded.

**Closed** 2016-03-31 22:31 UTC
Labels: Component: Request panel, enhancement
