### ISSUE TITLE
Tabs no longer supported

### ISSUE THREAD

**Issue by serialbandicoot** [jarrodek/ChromeRestClient#514] opened 2016-04-19 07:37 UTC
The Chrome Client open up a new window every time I create a new tab

## Expected outcome
What should happen? Well not this, as I've now got so many windows it would have been easier on 1 browser with multiple tabs.

## Actual outcome
What happened? So many windows.

## Versions
App: 7.7.26.168-stable
Chrome: 52.0.2709.0
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. Get latest Client
2. Open
3.

**Comment by jarrodek** [comment] 2016-04-19 10:55
Duplicate of #510

**Closed** 2016-04-19 10:55 UTC
