### ISSUE TITLE
If the response from a request is the text "null" it is treated as an actual empty null response

### ISSUE THREAD

**Issue by philmagr** [jarrodek/ChromeRestClient#705] opened 2016-06-14 15:40 UTC
As title. A bit of an edge-case, but weird nonetheless...

This is likely the same issue as https://github.com/jarrodek/ChromeRestClient/issues/670

## Expected outcome
"null" should be in the body

## Actual outcome
"The response was empty"

## Versions
App: 7.20.37.203-stable
Chrome: 51.0.2704.79
Platform: Windows (7)

## Steps to reproduce
1. Make a request to a server that returns a 4 character body of "null"

**Comment by jarrodek** [comment] 2016-06-14 16:25
Hi,

Thank you for issue report.

I'm guessing that the response's content-type is application/json? It's the only way to make the response falsy (false, null, empty string).

**For my reference:**
The issue is with `arc-response-payload-view` element and the `payload` property. It is using Polymer's template dom-if condition to determine if the response is empty. It should use the change observer and set up another property to determine if the response is empty, checking the type.

**Comment by philmagr** [comment] 2016-06-14 17:59
That is the response content-type yes.

**Comment by jarrodek** [comment] 2016-06-15 12:11
Fixed in https://github.com/jarrodek/ChromeRestClient/commit/eda48a48353ab0b8bc4218e67f7c61ccc062b0fe

**Closed by jarrodek** 2016-06-15 12:11 UTC
Labels: bug, Component: Response panel
