### ISSUE TITLE
the footer hides the send button

### ISSUE THREAD

**Issue by riyanka30** [jarrodek/ChromeRestClient#931] opened 2017-01-04 13:47 UTC
the footer sometimes does not stick to the bottom of the window and hides the data. In the attached sceenshot, it is hiding the send button.

## Expected outcome
the footer should remain at the bottom of the window

## Actual outcome
it is placed slightly above, which hides the response data or any other functionality

## Versions
App: 8.19.60.296-stable
Chrome: 55.0.2883.95
Platform: Mac OS X (10_11_6)

## Steps to reproduce.

 
<img width="1163" alt="screen shot 2017-01-04 at 7 14 41 pm" src="https://cloud.githubusercontent.com/assets/22613970/21644207/5f0d97a2-d2b2-11e6-9c36-6a08e682deeb.png">

**Comment by jarrodek** [comment] 2017-01-09 16:24
Hi,

Thank you for the issue report. Is this issue still happening? As per #901 it looks like it was resolved.

**Comment by riyanka30** [comment] 2017-01-09 16:35
Hi, I am using the version 8 and the latest available version of chrome. I see the issue coming all the time. You can try reproducing it by having a larger response for the API.

**Comment by jarrodek** [comment] 2017-01-17 18:52
I did and I can't reproduce it now. It was happening earlier but it was CSS issue but it was resolved few versions ago.

As you can see in the image below it is working fine:
![Uploading image.png…]()

I'm closing this issue as WAI but feel free to reopen it if needed.

**Closed by jarrodek** 2017-01-17 18:52 UTC
