### ISSUE TITLE
History works wrong. 

### ISSUE THREAD

**Issue by ezeswci** [jarrodek/ChromeRestClient#883] opened 2016-11-10 15:52 UTC
Your description here

## Expected outcome
History in order
What should happen?

## Actual outcome
History not in order
What happened?

## Versions
App: 8.9.53.279-stable
Chrome: 54.0.2840.71
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-11-10 16:22
Hi,
Thank you for the issue report.
Can you provide the screenshot of the history where it's ordered wrong? I'm can't reproduce order issues

**Comment by ezeswci** [comment] 2016-11-10 16:47
![bug](https://cloud.githubusercontent.com/assets/6862919/20185707/cf1237ac-a74b-11e6-9bb3-025467365451.png)

This dates ar wrong, this requests shown are at least 6 month old.

If its usefull as to track the bug, the problem began just after the update.

**Comment by jarrodek** [comment] 2016-11-10 17:42
I'm not sure if I can fix it now. It looks like the history items do not have time signature attached and therefore are pushed to the top of the list (as Indexed db would order it). For some reason during the update the time wasn't passed to new objects.
Each of this list items should have an hour of execution displayed (like the two in the middle). 
I'll try to correct it somehow but I'm not sure why it hasn't time in the first place. 

Can you [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) the app as show me a structure of one of this items in the data explorer? It should be here:
![image](https://cloud.githubusercontent.com/assets/3320020/20187629/ea9aafe2-a76c-11e6-93d9-a0e573c815ed.png)

Note that it might be the latest item in the datastore. It would help me with more debugging.

**Comment by jarrodek** [comment] 2016-11-10 17:50
Alternately you can try to run this command in the console:
```
chrome.storage.local.remove('upgrades')
```
And restart the app. **this will remove all data in the new databases and recreate the data from the old database**
It means that if you have saved some data since the upgrade they will be removed. But you may ise import / export options to saved data to file.

**Comment by ezeswci** [comment] 2016-11-10 17:56
![bug2](https://cloud.githubusercontent.com/assets/6862919/20188087/d5884068-a755-11e6-82ed-6bfe446f4dfc.png)
Hope it helps

**Comment by ezeswci** [comment] 2016-11-10 17:59
chrome.storage.local.remove('upgrades') --> I used it. After starting the app again it downloads the update again and same problem.

**Comment by jarrodek** [comment] 2016-11-10 18:29
I'm really sorry but I've pasted wrong database screenshot. History data that is showed on the history list is in the `_pouch_history-requests` database. I'am only interested if object has `updated` property set to a number (timestamp) and if the first part of the key is a number (something like `1478563200000`).

![image](https://cloud.githubusercontent.com/assets/3320020/20188851/706f5e06-a772-11e6-858f-2185057a5d4a.png)

The `updated`property is important because the app is sorting data on this property. The it uses first part of the key to compute header for history section.
I may have an explanation if the `updated` property is not set in the database. But if it is it may mean something different. So can you please send it again for right database?

**Comment by ezeswci** [comment] 2016-11-10 19:54
jarrodek tomorrow ill send you the screen shot, i am in a dificult day today!!

**Comment by ezeswci** [comment] 2016-11-11 14:38
![bug3](https://cloud.githubusercontent.com/assets/6862919/20218388/2a1ca30a-a803-11e6-95f0-23803aa5ce56.jpg)
Believe you were right, the problem is the updated url

**Comment by jarrodek** [comment] 2016-11-14 15:25
Thank you for the update. It looks like there was an issue during the update and the app didn't moved properties as designed. I'll try to find a fix for this issue very soon.

**Comment by jarrodek** [comment] 2016-11-14 16:35
Hi,

Two things.
I've managed to fix the issue in the code. Now it will check if the `updated` property exists before showing the data. It will use `created` instead if now. It's not that accurate like updated but there might be difference between minutes / hours because the history object is created once per day.

The fix will be published soon.

If you'd like to do it manually (meaning faster), you can use gist that I've  prepared for you: https://gist.github.com/jarrodek/ff0bedf1e006a215485898b22339a701
It will update the `updated` value if required.

Fix will be published soon.

**Closed by jarrodek** 2016-11-14 16:35 UTC
Labels: bug
