### ISSUE TITLE
No way to accept to continue with invalid certificates since ARC moved to desktop app

### ISSUE THREAD

**Issue by andrecr16** [jarrodek/ChromeRestClient#423] opened 2016-04-05 17:42 UTC
Sometimes when developing, you have invalid certificates, so in CHrome, you just choose to continue anyway.

ARC requests will not work until you use a separate window to accept to continue with the invalid certificate. That use to work since ARC was a web app, and shared the same session as other chrome tabs.

Now that ARC was converted into a desktop app, there's no way to accept to continue with the invalid certificate, so the requests are no longer working,

**Comment by jarrodek** [comment] 2016-04-05 17:44
Duplicate of #420

**Closed by jarrodek** 2016-04-05 17:44 UTC
