### ISSUE TITLE
[Request feature]: Increase font size of body content on new version

### ISSUE THREAD

**Issue by deverlex** [jarrodek/ChromeRestClient#1063] opened 2017-10-15 16:00 UTC
Hi,

At new this version, I feel font size of body content very small, your team can increase it or make a function allow change font size?
Thanks

## Versions
App: 10.0.3
Platform: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by jarrodek** [comment] 2017-10-16 17:49
Hi,
Thank you for the issue report. I'm marking it as a duplicate of #1072 since I answered there already.
I'll update the app in a minute.

**Closed by jarrodek** 2017-10-16 17:49 UTC
