### ISSUE TITLE
Session cookies aren't being used by ARC

### ISSUE THREAD

**Issue by RanGold** [jarrodek/ChromeRestClient#531] opened 2016-04-19 13:42 UTC
ARC working not as a tab causing the request to be without the session cookies.
This makes it harder on debuging exisiting session requests

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (7)

**Comment by jarrodek** [comment] 2016-04-19 14:53
Duplicate of #487

**Closed by jarrodek** 2016-04-19 14:53 UTC
