### ISSUE TITLE
URL encode problem

### ISSUE THREAD

**Issue by klightshadow** [jarrodek/ChromeRestClient#649] opened 2016-05-04 07:24 UTC
URL encode wrong in chinese

value input 減肥
## Expected outcome
%E6%B8%9B%E8%82%A5

## Actual outcome
%1B%C2%A5

## Versions
App: 7.12.30.183-stable
Chrome: 50.0.2661.94
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. add query parameters
2. param value type "減肥"
3. send

**Comment by Izuzusama** [comment] 2016-05-04 09:50
Tested on Windows 10, Encodes correctly
![encode](https://cloud.githubusercontent.com/assets/9895213/15010794/a5319556-1220-11e6-93cc-f8e66cdf1dad.png)

**Comment by jarrodek** [comment] 2016-05-04 13:20
Thank you for issue report.
I'll look into it.

**Comment by jarrodek** [comment] 2016-05-09 19:08
@klightshadow i can't reproduce this problem. It is working in Ubuntu, Mac OS and Windows. Can you think of any factor that could cause this behaviour on your machine?

**Comment by klightshadow** [comment] 2016-05-10 01:24
@jarrodek I'm working on Mac OS_10.11.4, tomcat_7, JAVA Jersey_2.22.1
Here are two pictures about the bug
![2016-05-10 9 11 07](https://cloud.githubusercontent.com/assets/8789346/15132853/2028628a-1690-11e6-82f7-6c46f83e5a73.png)
<img width="592" alt="2016-05-10 9 11 24" src="https://cloud.githubusercontent.com/assets/8789346/15132854/2028baf0-1690-11e6-99e8-1f3a46fb226b.png">

the "searche_content" value is "減肥", however the request show "¥"

**Comment by jarrodek** [comment] 2016-05-10 18:36
@klightshadow thanks for detailed explanation. 
The transport library is using Uint8Array object which causing the problem with this characters. This is obviously a bug. The library should use TextEncoder/TextDecoder API to transform text to array buffer and back.
I've added an issue in the transport library (https://github.com/jarrodek/socket-fetch/issues/12) that you can follow to check when it will be fixed.

**Closed** 2016-05-10 20:50 UTC
Labels: bug
