### ISSUE TITLE
New footer bar overlapping SEND button with long payload

### ISSUE THREAD

**Issue by Diesisbj** [jarrodek/ChromeRestClient#863] opened 2016-11-08 17:02 UTC
Your description here
![helloooo-genus](https://cloud.githubusercontent.com/assets/23342098/20108633/00fa963a-a5dd-11e6-8fbb-1d395e58d4f6.png)
New footer bar overlapping SEND button with long payload. Impossible to send message.
Screen resolution 1920x1080

## Expected outcome
The footer bar should not hide the send button

## Actual outcome
What happened?

## Versions
App: 8.6.52.275-stable
Chrome: 54.0.2840.71
Platform: Windows (10)

## Steps to reproduce
1. put a long json payload in the payload form
2. 
3.

**Comment by jarrodek** [comment] 2016-11-08 17:13
Hi,

Thank you for the issue report. It's a duplicate of #837. 

The issue is fixed and when I'll finish with #830 I'll release the update.

**Closed by jarrodek** 2016-11-08 17:13 UTC
