### ISSUE TITLE
[enhancement] ability to sort the list of project endpoints

### ISSUE THREAD

**Issue by justinhelmer** [jarrodek/ChromeRestClient#358] opened 2016-01-13 19:52 UTC
As a project grows, the list of `APIs` tends to grow along with it. Having project-level endpoints is a tremendously useful feature.

That being said, the list grows long enough such that it can be difficult to find what you are looking for. It appears they are currently sorted based on timestamp, or some sort of natural sort order.

It would be very useful to be able to sort endpoints to suit the needs of the team. I understand this is not a small request and must be considered a longer term potential enhancement.

I think you will find many others will benefit from this as well.

**Comment by justinhelmer** [comment] 2016-01-13 19:53
**Not** a duplicate of [#357](https://github.com/jarrodek/ChromeRestClient/issues/357)

**Comment by jarrodek** [comment] 2016-01-13 23:48
It's a duplicate of #340  :)
It's on my roadmap. I can't do it right now but it will be don in a matter of weeks.

**Closed by jarrodek** 2016-01-13 23:48 UTC
