### ISSUE TITLE
Chrome 56 Support for Post Request Multipart/form-data

### ISSUE THREAD

**Issue by Newtons4thLaw** [jarrodek/ChromeRestClient#952] opened 2017-02-08 20:30 UTC
ARC no longer works properly with Chrome 56 when using POST request with Content-Type: multipart/form-data

## Expected outcome
What should happen?
Send the file as content

## Actual outcome
What happened?
Does not send the file as part of the multipart/form-data content

## Versions
App: 8.19.60.296-stable
Chrome: 56.0.2924.87
Platform: Windows (10)

## Steps to reproduce
1.  Make a POST request with Content-Type: multipart/form-data while attaching a file
2.  IIS will always return "415: Unsupported Media Type"
3.  The exact same process will function normally in Chrome version 55 or older.

**Comment by jarrodek** [comment] 2017-02-11 01:15
Hi,

Thank you for the issue report.
It is a duplicate of #945. Please, refer to this issue for more information.

**Closed by jarrodek** 2017-02-11 01:15 UTC
