### ISSUE TITLE
Error when GET a text/plain file

### ISSUE THREAD

**Issue by angelynzhou** [jarrodek/ChromeRestClient#430] opened 2016-04-06 16:25 UTC
With the upgraded ARC version, when I do GET on an endpoint that returns a plain text file (text/plain), I don't get the "Parsed" output. It gave me error "Uncaught ReferenceError: mime is not defined". If I click on "Raw" output, it gave me the text contents but no line separations. With the previous ARC version, I got the text file fine - shown line by line.

-- this image shows the error
![image](https://cloud.githubusercontent.com/assets/18286957/14324394/9a5f518e-fbf2-11e5-8bd2-22af4a8bb852.png)

-- this image shows the Raw output without line separation
![image](https://cloud.githubusercontent.com/assets/18286957/14324406/a47bd9ee-fbf2-11e5-815d-2aefdebf4ca8.png)

**Comment by jarrodek** [comment] 2016-04-06 16:33
Duplicate of #424. It's in beta release. In coming days it will be updated in stable channel.

**Closed by jarrodek** 2016-04-06 16:33 UTC

**Comment by angelynzhou** [comment] 2016-04-06 16:37
Great. Thanks!!
