### ISSUE TITLE
Advanced Rest Client

### ISSUE THREAD

**Issue by kachhawayamehulgmailcom** [jarrodek/ChromeRestClient#959] opened 2017-02-20 07:21 UTC
The Content Type Header Will finally Changed Into "multipart/form-data" During Request.

## Expected outcome
I am using header type "application/x-www-form-urlencoded"
And Sumitt other parameters from here.
And using FileUpload for upload image few day ago i am cheaking my api via these. it's working fine,means all data with image url is summit in data base.

## Actual outcome
Now while i am not upload image it's working fine,but while use upload image,it's not getting parametres.
## Versions
App: 8.19.60.296-stable
Chrome: 56.0.2924.87
Platform: Windows (8.1)

**Comment by vishakhakadamjalindar** [comment] 2017-02-20 11:27
i have  same error when uploading file also form data it gives empty parameter

**Comment by kachhawayamehulgmailcom** [comment] 2017-02-20 12:02
I am facing these problem from today. before it's working fine.

**Comment by vishakhakadamjalindar** [comment] 2017-02-20 13:36
Hi,
Actually, I am also facing the file uploading problem using Rest Clent
tool. Can you tell me what the actual problem?
Becoz the backend code is correct.

**Comment by kachhawayamehulgmailcom** [comment] 2017-02-20 13:41
Buddy I really don't knew, what problem you are facing exact way.
But as far as concer about my problem in my case it is related with Contenttype headers.

**Comment by jarrodek** [comment] 2017-02-20 20:24
Hi,

This is confirmed bug in Chrome. And this is duplicate of #945. I'm currently working on a solution.

I'm closing it as a duplicate.

**Closed by jarrodek** 2017-02-20 20:24 UTC
