### ISSUE TITLE
Broken charset in new version

### ISSUE THREAD

**Issue by vGhost2000** [jarrodek/ChromeRestClient#1065] opened 2017-10-16 05:42 UTC
Broken charset in new version:

## Expected outcome
http://prntscr.com/gxxtcn

## Actual outcome
http://prntscr.com/gxxsux

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. do any query

**Comment by jarrodek** [comment] 2017-10-16 15:56
Than you for the issue report.
I'm marking this as a duplicate of #1065 since i've started conversation there.`

**Closed by jarrodek** 2017-10-16 15:56 UTC
