### ISSUE TITLE
web socket reconnect

### ISSUE THREAD

**Issue by etricky** [jarrodek/ChromeRestClient#728] opened 2016-07-22 12:58 UTC
Your description here
While using a web socket that requires authentication, if the connection is closed due to timeouts or the authentication fails it keeps reconnecting with no option to stop the connection attempts
## Expected outcome
What should happen?
Either a configuration with the number of reconnects or an option/button to stop the connection attempts should be available
## Actual outcome
What happened?
No way to stop the application to reconnect, must kill the app to stop it
## Versions
App: 7.20.37.203-stable
Chrome: 51.0.2704.106
Platform: Windows (10)

## Steps to reproduce
1. Connect to a web socket with the wrong credentials or a web socket that does not exists
2. 
3.

**Comment by jarrodek** [comment] 2016-07-25 16:20
Hi,

Thank you for issue report. It is a duplicate of #711.
It's in the feature branch already and will be published soon.

**Closed** 2016-07-25 16:24 UTC
