### ISSUE TITLE
stuck if response body is an invalid json content

### ISSUE THREAD

**Issue by dawncold** [jarrodek/ChromeRestClient#450] opened 2016-04-09 03:42 UTC
**if you get an invalid json response content, ARC will stuck on waiting for response status.**
## Expected outcome
What should happen?
**display all response content**
## Actual outcome
What happened?
**if you get an invalid json response content, ARC will stuck on waiting for response status.**
## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Linux (-)

## Steps to reproduce
1. request with a response is application/json, but can not be parsed json response body, just like this one: 

```
{"subscribe":1,"openid":"oiO6ajshaq1BAEDwB1s1DfIvl2iw","nickname":"王晓妞","sex":2,"language":"zh_CN","city":"WÎ","province":"SN¬","country":"","headimgurl":"http:\/\/wx.qlogo.cn\/mmopen\/6JvjksOfUHZYgMpM4yzIOzHrh64ibhN6rt3c51vvUVqzw1Cnes4sxq04OhibUjqlbyx1VFR7DFpS2SJlSyAmfiauQ\/0","subscribe_time":1390536194,"unionid":"oISWWuNpcYepdt2R-O_hCq3EaCUM","remark":"","groupid":0}
```

this is what I get from wechat (a famous chat tool in China)

**Comment by jarrodek** [comment] 2016-04-11 15:56
I can't reproduce the problem:
![image](https://cloud.githubusercontent.com/assets/3320020/14433459/4b09c30e-0006-11e6-8c71-4b97904fd2bb.png)

Can you attach a file with the data and tell me what is the encoding of the file? Then I'll try to reproduce the problem again.

**Comment by dawncold** [comment] 2016-04-12 01:59
Hi @jarrodek 

you should use this json content which included some control character, like \x17, etc

```
{"subscribe":1,"openid":"oiO6ajshaq1BAEDwB1s1DfIvl2iw","nickname":"\xe7\x8e\x8b\xe6\x99\x93\xe5\xa6\x9e","sex":2,"language":"zh_CN","city":"\xc2\x89\x7fW\xc3\x8e","province":"S\x17N\xc2\xac","country":"","headimgurl":"http:\\/\\/wx.qlogo.cn\\/mmopen\\/6JvjksOfUHZYgMpM4yzIOzHrh64ibhN6rt3c51vvUVqzw1Cnes4sxq04OhibUjqlbyx1VFR7DFpS2SJlSyAmfiauQ\\/0","subscribe_time":1390536194,"unionid":"oISWWuNpcYepdt2R-O_hCq3EaCUM","remark":"","groupid":0}
```
I pasted before had been encoded by utf8, so you can't find the issue.

I use python standard library json to parse this json, it doesn't work unless I pass a `strict=False` to `json.loads`.  https://docs.python.org/2/library/json.html#json.JSONDecoder

**Comment by jarrodek** [comment] 2016-04-21 11:04
This should be fixed already as per https://github.com/jarrodek/ChromeRestClient/commit/6ea9c8a6d511087104c3d7157e1b52ca25f2e563

**Closed by jarrodek** 2016-04-21 11:04 UTC
Labels: bug
