### ISSUE TITLE
The new update does not work with credentials true 

### ISSUE THREAD

**Issue by ezeswci** [jarrodek/ChromeRestClient#539] opened 2016-04-19 18:19 UTC
Use App

## Expected outcome
App response

## Actual outcome
"error": "You need to sign in or sign up before continuing."

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Windows (10)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-04-20 11:05
Duplicate of #487

**Closed by jarrodek** 2016-04-20 11:05 UTC
