### ISSUE TITLE
Advanced rest client sent button issue

### ISSUE THREAD

**Issue by vigitha** [jarrodek/ChromeRestClient#847] opened 2016-11-08 08:39 UTC
After version up gradation, Send button is almost hidden by the explore button.Need some sort of skill to click on the send button.

**Comment by domints** [comment] 2016-11-08 11:11
Exactly, especially when request content is long, like on screenshot below.
![image](https://cloud.githubusercontent.com/assets/1096161/20096973/802eb32c-a5ac-11e6-94b3-0edd28b11a46.png)

**Comment by domints** [comment] 2016-11-08 11:12
Especially when request is long, like on SS below:
![image](https://cloud.githubusercontent.com/assets/1096161/20097004/a32db0c6-a5ac-11e6-97b6-e2f16ed7f551.png)

**Comment by jarrodek** [comment] 2016-11-08 12:51
Hi thank you for the issue report.
I missed that earlier (I've checked it out though).
I'm on the fix right now.

**Comment by jarrodek** [comment] 2016-11-08 13:04
And it's actually a duplicate of #837 so I'm closing it right now. And I'm working on a fix as well.

**Closed by jarrodek** 2016-11-08 13:04 UTC
Labels: bug
