### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by axing** [jarrodek/ChromeRestClient#893] opened 2016-11-15 04:23 UTC
If PC doesn't connect to internet, when launching the app it will consume a lot of memory and some CPU usage. 
Tried clear all history, projects, saved links but issue still persists.
Tried reinstall the app but still doesn't fix the issue.

## Expected outcome
Memory shouldn't leak.

## Actual outcome
Memory leaks from initial 50MB to 1GB (probably still going up, but I killed the app when reaching 1GB+). CPU usage around 25-30% (Intel i3 4 cores).

## Versions
App: 8.9.53.279-stable
Chrome: 54.0.2840.71
Platform: Windows (8.1)

## Steps to reproduce
1. Disconnect completely from internet.
2. Launch the app.
3. Now watch the memory hogging party on task manager.

**Comment by jarrodek** [comment] 2016-11-21 18:26
Hi,

Thank you for issue report.
I'm investigating it but as you may be aware it's not what comes easily. 

I can reproduce the problem but only sometimes. I already spent few hours reading profile result without success. I have found one issue with the memory but it's rather minor issue and should not cause big memory issues.

I'm working on it and I'll update you when find something.

**Comment by Nem3sis89** [comment] 2017-02-15 09:31
Hi, i'm experiencing the same issue with Chrome 56.0.2924.87 (64-bit) and Windows 10. Is there any way to get a previous version of this client? 

thank you for your work

**Comment by jarrodek** [comment] 2017-02-23 23:14
This issue might be related to the API assistant added to ARC in this version. I couldn't notice anything because at home and at work my computers are rather strong. 
In today's release I've disabled the assistant by default and can be enabled in settings. This change will prohibit background data analysis and therefore will limit memory usage by the app.

It should resolve this issue so I am closing it. Feel free to reopen if needed.

**Closed by jarrodek** 2017-02-23 23:14 UTC
Labels: bug
