### ISSUE TITLE
POST requests fall into infinite loops with Cookie header being set

### ISSUE THREAD

**Issue by bigunyak** [jarrodek/ChromeRestClient#616] opened 2016-04-25 11:35 UTC
POST requests fall into infinite loops with Cookie header being set.

## Expected outcome
Well, should be one request only...

## Actual outcome
ARC generates infinite number of POST requests.

## Versions
App: 7.7.26.168-stable
Chrome: 50.0.2661.75
Platform: Linux (-)

## Steps to reproduce
1. Build a POST request.
2. Set Cookie header.
3. Fire the request.

On a side note, man, how come you released such a major upgrade with sooo many problems without possibility to rollback...?

**Comment by bigunyak** [comment] 2016-04-25 11:38
It was such a helpful nice application to use and now... ehh, sigh...

**Comment by jarrodek** [comment] 2016-04-25 21:11
Hi,

Thank you for issue report.

I can't reproduce the problem. Can you clarify what's happening? Are you sure that the server have not closed loop in redirection? Maybe you can paste some logs from the logger (left nav > bottom of the panel > more button).

**Comment by bigunyak** [comment] 2016-05-04 13:39
Trying to reproduce the problem and can not do it because of another problem, I can't get rid of Cookies now, they are attached to all my requests, no matter what I do.
* I checked that there are no cookies in the browser.
* No cookies in the Raw headers form.

And yet I always get the attached Cookies to the requests, restarted the app and the browser, nothing helps.
Any suggestions?

**Comment by jarrodek** [comment] 2016-05-04 13:43
YOu can clear cookies in settings. If you disable cookie collection this mechanism will not work at all (cookies won't be added to the requests automatically and won't be stored).
Not that it is working as a browser would work in cookie management.

**Comment by bigunyak** [comment] 2016-05-04 13:51
OK, thanks! Finally got rid of them!
And the original problem with infinite requests loop is still there. It doesn't seem to have anything to do with Cookies though, so my initial suggestion is wrong.
The problem happens when the server is trying to redirect the client with 302, the `Location` header is set to a different URL of course.

**Comment by jarrodek** [comment] 2016-05-04 14:07
So I guess the app is doing well because it is redirecting the request to new URL. If you have an infinite loop in the server (e.g. redirecting from one URL to another and then back to original one) then you have this issue. The app is applying server request.
However there should be an error thrown in this cases like chrome's Error 310 (net::ERR_TOO_MANY_REDIRECTS).

**Comment by bigunyak** [comment] 2016-05-04 15:12
I think I finally got to the root of the problem.
Let's see what's happening step by step.
* I do a POST request to the login form with user credentials.
* The server responds with 302 redirect to success page and sets session cookies. Apparently the app ignores these cookies (with Collect Cookies enabled in the Settings)!
* Next the app gets to the success page and since there are no session cookies set, the server responds with 302 redirect back to the login page.
* App does the **same** original POST request to the login page and authenticates me again!
* That's it, I'm in the infinite loop now.

So, questions are the following:
* Why cookies ignored in responses with redirect.
* Why the application keeps sending the same POST request when with 302 the client should not follow the redirect automatically for POST/PUT/DELETE requests.

**Comment by jarrodek** [comment] 2016-05-04 22:04
Hi,

Thanks for detailed information. It's helpful.

As for the cookies, the app is following session management spec with cookie match algorithms included in the spec. As per test conducted on cookie storage it works as intended. However if there's an issue there it would be helpful if you could add an information of:
- what's the domain and path parameter of the cookies set by server. If not set then the request url's domain and path
- what's the redirection domain and path
Cookies probably were stored in the session store but not included in the response since the domain or path did not matched (at leas according to the spec).

As for a redirection:

> RFC 1945 and RFC 2068 specify that the client is not allowed
>       to change the method on the redirected request.  However, most
>       existing user agent implementations treat 302 as if it were a 303
>       response, performing a GET on the Location field-value regardless
>       of the original request method. The status codes 303 and 307 have
>       been added for servers that wish to make unambiguously clear which
>       kind of reaction is expected of the client.

If most user agents actually do this I think I can make this exception in the app. However right now it follows the spec.

Thanks to this issue I just found another issue:

> The different URI SHOULD be given by the Location field in the response. Unless the request method was HEAD, the entity of the response SHOULD contain a short hypertext note with a hyperlink to the new URI(s).

Now the transport library only follows redirection only when the Location header is present in the response. It should also check the response body for the URL.

**Comment by elipoultorak** [comment] 2016-05-05 15:22
I have a similar problem, and what was causing the problem is that:
- the cookie is set by the server and is url-encoded. For example, + is %2B
- the cookie is then put in the ARC storage decoded.
- when it's sent again to the server, it uses "Cookie: xxx+xxx" instead of url-encoding it. That means the server will convert it to a space, and it doesn't match the original cookie.

**Comment by jarrodek** [comment] 2016-05-06 22:07
@elipoultorak I think it is a separate issue here for cookie parsing and sending.

**Comment by jarrodek** [comment] 2016-05-09 19:16
The 302 status issue has been resolved in referenced issue. Soon it will be released in beta and then stable channel.

**Closed by jarrodek** 2016-05-09 19:16 UTC
Labels: awaiting-response
