### ISSUE TITLE
Settings bar overlapped results

### ISSUE THREAD

**Issue by Zulqurnain** [jarrodek/ChromeRestClient#901] opened 2016-11-21 23:23 UTC
Bottom bar is overlapping with results: 
http://i.imgur.com/undefined.png

## Expected outcome
What should happen?
it should not overlap at all

## Actual outcome
What happened?
i don't know see yourself

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.71
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. Like
2. I
3. Care

**Comment by jarrodek** [comment] 2016-11-22 16:16
Hi,.

Something's wrong with your image URL. Can you please attach the image again? A tip: you can just paste the image from the clipboard in the text editor here.

**Comment by ghowen** [comment] 2016-12-18 15:15
Same here. See screenshot.

App: 8.19.60.296
Chrome: 55.0.2883.95
Platform: Max OS X (10.12.2)


![rest client](https://cloud.githubusercontent.com/assets/390784/21294449/97c49f90-c534-11e6-95af-6c4ef4f184aa.png)

**Comment by jarrodek** [comment] 2017-01-06 19:37
Hi,

Thank you for the update.
Is it happening all the time or is happening only for a specific condition?
I'm asking because I have difficulties with reproducing the issue.

**Comment by ghowen** [comment] 2017-01-07 09:17
Hi,

it used to happen all the time but maybe 1 week ago it stopped. I thought there might have been an update that resolved the issue, but did not follow up. If there was no update from your side there might have been a new release of Chrome that solved this. Anyways, all is good for now. Thanks for checking in!

**Comment by jarrodek** [comment] 2017-01-09 16:22
Hi,

Thanks for the update.
There were no updates in last few weeks. So I'm guessing there were some issues with the Chrome and Web Components. 

I'm closing this but it the problem returns, please, let me know.

**Closed by jarrodek** 2017-01-09 16:22 UTC
Labels: awaiting-response
