### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by Aztherion** [jarrodek/ChromeRestClient#695] opened 2016-06-04 20:03 UTC
GET request where the ID part of the URI begins with "123" fails with the message in the caption. 

ex. 
GET http://localhost:8194/api/sample/086B825C-D1D0-4E6E-9414-59060DE2CD2
works fine

GET http://localhost:8194/api/sample/123B825C-D1D0-4E6E-9414-59060DE2CD2
fails. 

GET http://localhost:8194/api/samplestringmethod/ABC
works fine

GET http://localhost:8194/api/samplestringmethod/123
fails. 

GET http://localhost:8194/api/samplestringmethod/124
works fine. 

I've also verified that the web server aren't receiving the failing requests, so the problem isn't on that end.

**Comment by jarrodek** [comment] 2016-06-06 10:56
Hi,

Thank you for the issue report. 
Can you paste an error log from log viewer? (It's in "more" option in left panel). I can't reproduce the problem myself and it may help debug the issue.

**Comment by Aztherion** [comment] 2016-06-07 07:32
Hi, 
I restarted the client and now I can't seem to reproduce it. Will let
you know if the problem re-appears. 
//Benny 

----- Ursprungligt meddelande -----
Från: "jarrodek/ChromeRestClient" 
Till:"jarrodek/ChromeRestClient" 
Kopia:"Benny Olsson" , "Author" 
Skickat:Mon, 06 Jun 2016 03:56:43 -0700
Ämne:Re: [jarrodek/ChromeRestClient] Cannot read property
'toUpperCase' of undefined (#695)

	Hi, 

	Thank you for the issue report. 
 Can you paste an error log from log viewer? (It's in "more" option in
left panel). I can't reproduce the problem myself and it may help
debug the issue. 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or mute the
thread [2].     

Links:
------
[1]
https://github.com/jarrodek/ChromeRestClient/issues/695#issuecomment-223927616
[2]
https://github.com/notifications/unsubscribe/ABoaNfVXPtomGauXuWESozwfZTgc53z8ks5qI_zrgaJpZM4IuNQw

**Comment by jarrodek** [comment] 2016-06-07 10:57
There is a possibility that the app just updated itself and the issue was related to previous version.
I'm closing this issue for now. If it occur again, please, reopen it.

**Closed by jarrodek** 2016-06-07 10:57 UTC
Labels: awaiting-response
