### ISSUE TITLE
Since the update there's no way to ignore an unrecognized SSL certificate.

### ISSUE THREAD

**Issue by denisariel** [jarrodek/ChromeRestClient#463] opened 2016-04-11 16:22 UTC
Your description here
I'm working with a debug server that desn't have a valid SSL certificate. The previous version worked fine if a rule was created in chrome. With this version I just  a ERR_CERT_COMMON_NAME_INVALID error and there is no (apparent) way to instruct the app to ignore the certificate and accept the response

## Expected outcome
What should happen?
should get the response, since there's a rule created in chrome

## Actual outcome
What happened?
ERR_CERT_COMMON_NAME_INVALID

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1. find a web server that doesn't have a valid ssl certificate
2. open the web site with chrome, after the regular security prompts create a rule to ignore this error for this site and access the site regularly
3. try to make the same call with the app
4. You will get an error of type ERR_CERT_COMMON_NAME_INVALID

**Comment by jarrodek** [comment] 2016-04-11 16:33
Duplicate of #432 (sort of but it's all leading to the same issue - the cert is not installed in the system)

**Closed by jarrodek** 2016-04-11 16:33 UTC
