### ISSUE TITLE
Copy Content to clipboard button not working after recent update 

### ISSUE THREAD

**Issue by UsmanGhauri** [jarrodek/ChromeRestClient#1076] opened 2017-10-16 15:32 UTC
Your description here
Copy to clipboard button for json response is not working
![screenshot_1](https://user-images.githubusercontent.com/10024551/31620539-309ed3d0-b2a0-11e7-98ec-06a8b5eefb52.png)

## Expected outcome
What should happen?
should copy json response to clipboard

## Actual outcome
What happened?
not copying the response to clipboard

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1.  send any api request 
2.  on response copy the value and try pasting it to somewhere there is not data copied to clipboard

**Comment by jarrodek** [comment] 2017-10-16 15:54
Hi,
Thank you for the issue report. This is duplicate of #1070 .
Also I just fixed it. I'll release the update in an hour or so.

**Closed by jarrodek** 2017-10-16 15:54 UTC
