### ISSUE TITLE
Import seems to work, but nothing saved

### ISSUE THREAD

**Issue by uyhung** [jarrodek/ChromeRestClient#375] opened 2016-02-02 06:57 UTC
I export history from other computer, then try to import into another computer. Before importing, I see the list of requests, then after click Import button the page get reloaded without any error and a popup shown at the left bottom corner of the page saying that "Data Saved". But after checking the Projects and the History tab, none of the requests is shown.

Please fix it. What is the point of supporting export but not import?

**Comment by duane5000** [comment] 2016-02-02 19:38
I saw the same. Closing Rest client and opening now shows duplicate of all my projects

**Comment by jarrodek** [comment] 2016-02-02 20:46
This is a duplicate of #372. Kind of but it's the same issue with import.

**Closed** 2016-02-06 02:30 UTC
Labels: bug
