### ISSUE TITLE
When patched done, the progress is still running

### ISSUE THREAD

**Issue by dunght160387** [jarrodek/ChromeRestClient#698] opened 2016-06-08 01:45 UTC
Do a Patch.
## Expected outcome

when patched => done, not in progress
## Actual outcome

when patched => not exist progress, still running with button "abort" to abort progress
## Versions

App: 7.20.37.203-stable
Chrome: 47.0.2526.106
Platform: Linux (-)
## Steps to reproduce
1. do a patch to REST api
2. see bug

p/s: i see many bugs and i don't like the new ui, i want to use old ui.

**Comment by jarrodek** [comment] 2016-06-08 15:47
Hi,

Thank you for issue report.
I can't reproduce the problem. It looks like it is not related to method used with the request.

Can you see any error message in the log viewer? It is located in left panel under "more".


As for the UI I prefer to keep one issue per issue report. If you have particular issues with the UI, pleas, file new issue report / feature request.

Thanks.

**Comment by dunght160387** [comment] 2016-08-05 04:12
Hi, 

Thanks for your reply;
I made a normal PATCH request, then server (my own api server) returned http response with code 204.
Is there any wrong things here???

Rgds.

**Comment by jarrodek** [comment] 2016-08-08 18:38
Hi,

The response panel should display something like: 
![image](https://cloud.githubusercontent.com/assets/3320020/17491428/8325ecd0-5d9f-11e6-92e0-90dd28967660.png)

I noticed that you are using some old version of the app. There were some issues before with this status but it was fixed. So probably in current version (7.26...) it is working as it should. 
Can you please check it so I can close the issue?

**Comment by jarrodek** [comment] 2016-08-08 18:40
(That was a path request to http://httpbin.org/status/204)

**Comment by jarrodek** [comment] 2017-01-17 19:21
This issue has been fixed already.

**Closed by jarrodek** 2017-01-17 19:21 UTC
Labels: awaiting-response
