### ISSUE TITLE
Search is slow

### ISSUE THREAD

**Issue by DivyaSelvaraj** [jarrodek/ChromeRestClient#653] opened 2016-05-06 10:32 UTC
When I search for a text after I get the response for my request, it really takes more than 3 secs to show the text which I entered.

## Expected outcome
It should show as soon as I typed the text.

## Actual outcome
There was a delay in showing the text in the search box. 

## Versions
App: 7.16.33.191-stable
Chrome: 50.0.2661.94
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. Make a API request, Wait for the response to load.
2. Now try to search some text in the response.
3. See the delay in showing the text in the search box.

**Comment by jarrodek** [comment] 2016-05-06 22:10
Hi,
Thanks for issue report.
It is a duplicate of #566.

**Closed** 2016-05-09 19:03 UTC
Labels: Duplicate
