### ISSUE TITLE
Open a new Window button won't work all the time

### ISSUE THREAD

**Issue by AlarkaSanyal** [jarrodek/ChromeRestClient#813] opened 2016-10-04 20:23 UTC
Your description here
## Expected outcome

What should happen?
## Actual outcome

What happened?
## Versions

App: 7.39.48.260-stable
Chrome: 53.0.2785.116
Platform: Windows (7)
## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment] 2016-10-05 15:24
Hi,

Thank you for issue report. I can't confirm this behaviour. Can you provide any debug information from the background page? Wee wiki for more information.

**Comment by jarrodek** [comment] 2016-11-07 12:50
I'm  closing this issue as I can't reproduce the problem and additional information can't be provided.

**Closed by jarrodek** 2016-11-07 12:50 UTC
Labels: awaiting-response
